# LLM configuration for iEcoreGen MWE2 workflow

url=https://openrouter.ai/api
timeout=1800
apikey=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
model=deepseek/deepseek-v3.2-exp