# LLM configuration for iEcoreGen MWE2 workflow

url=https://openrouter.ai/api
timeout=1800
apikey=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
model=deepseek/deepseek-v3.2-exp