/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell Stack</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.CellStack#getCount <em>Count</em>}</li>
 *   <li>{@link edu.pa19.CellStack#getStack <em>Stack</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getCellStack()
 * @model kind="class"
 * @generated
 */
public class CellStack extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getCount() <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCount()
   * @generated
   * @ordered
   */
  protected static final int COUNT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCount() <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCount()
   * @generated
   * @ordered
   */
  protected int count = COUNT_EDEFAULT;

  /**
   * The cached value of the '{@link #getStack() <em>Stack</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStack()
   * @generated
   * @ordered
   */
  protected EList<FillableCell> stack;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CellStack()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.CELL_STACK;
  }

  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see edu.pa19.Pa19Package#getCellStack_Count()
   * @model
   * @generated
   */
  public int getCount()
  {
    return count;
  }

  /**
   * Sets the value of the '{@link edu.pa19.CellStack#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCount the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  public void setCount(int newCount)
  {
    int oldCount = count;
    count = newCount;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.CELL_STACK__COUNT, oldCount, count));
  }

  /**
   * Returns the value of the '<em><b>Stack</b></em>' containment reference list.
   * The list contents are of type {@link edu.pa19.FillableCell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stack</em>' containment reference list.
   * @see edu.pa19.Pa19Package#getCellStack_Stack()
   * @model containment="true"
   * @generated
   */
  public EList<FillableCell> getStack()
  {
    if (stack == null)
    {
      stack = new EObjectContainmentEList<FillableCell>(FillableCell.class, this, Pa19Package.CELL_STACK__STACK);
    }
    return stack;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a FillableCell to the top of the stack (after a placement).
   * Algorithm:
   *   1. Increment count by 1.
   *   2. Add the cell to the end of the stack list.
   * Related Features: count, stack.
   * Related Classes: FillableCell.
   * Input:
   *   - cell: The FillableCell to push. Must not be null.
   * Output: None (void).
   * Pre-condition: cell is a valid FillableCell (non-null).
   * Post-condition:
   *   - The stack size is increased by 1.
   *   - The count attribute is incremented by 1.
   *   - The last element of stack is the input cell.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void push(final FillableCell cell)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes and returns the last FillableCell placed on the stack (for undo).
   * Algorithm:
   *   1. If stack is empty, return null (or throw exception).
   *   2. Decrement count by 1.
   *   3. Remove the last element from stack and return it.
   * Related Features: count, stack.
   * Related Classes: FillableCell.
   * Input: None.
   * Output: The last FillableCell that was pushed, or null if stack is empty.
   * Pre-condition: None.
   * Post-condition:
   *   - The stack size is reduced by 1.
   *   - The count attribute is decremented by 1.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public FillableCell pop()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns the number of undo operations available (i.e., the number of cells in the stack).
   * Algorithm:
   *   1. Return the value of the count attribute.
   * Related Features: count.
   * Related Classes: None.
   * Input: None.
   * Output: An integer >= 0 representing the number of cells in the stack.
   * Pre-condition: None.
   * Post-condition: The stack state is unchanged.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public int getUndoCount()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Displays the current state of the CellStack (e.g., for debugging or UI).
   * Algorithm:
   *   1. Print the stack's count (number of elements).
   *   2. Optionally, print each cell in the stack (e.g., their coordinates).
   * Related Features: count, stack.
   * Related Classes: FillableCell.
   * Input: None.
   * Output: None (void). Output is printed to console or UI.
   * Pre-condition: None.
   * Post-condition: The stack state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void display()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.CELL_STACK__STACK:
        return ((InternalEList<?>)getStack()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.CELL_STACK__COUNT:
        return getCount();
      case Pa19Package.CELL_STACK__STACK:
        return getStack();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.CELL_STACK__COUNT:
        setCount((Integer)newValue);
        return;
      case Pa19Package.CELL_STACK__STACK:
        getStack().clear();
        getStack().addAll((Collection<? extends FillableCell>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.CELL_STACK__COUNT:
        setCount(COUNT_EDEFAULT);
        return;
      case Pa19Package.CELL_STACK__STACK:
        getStack().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.CELL_STACK__COUNT:
        return count != COUNT_EDEFAULT;
      case Pa19Package.CELL_STACK__STACK:
        return stack != null && !stack.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (count: ");
    result.append(count);
    result.append(')');
    return result.toString();
  }

} // CellStack
