/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.Cell#getCoord <em>Coord</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getCell()
 * @model kind="class" abstract="true"
 * @generated
 */
public abstract class Cell extends MinimalEObjectImpl.Container implements MapElement
{
  /**
   * The cached value of the '{@link #getCoord() <em>Coord</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoord()
   * @generated
   * @ordered
   */
  protected Coordinate coord;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Cell()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.CELL;
  }

  /**
   * Returns the value of the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coord</em>' containment reference.
   * @see #setCoord(Coordinate)
   * @see edu.pa19.Pa19Package#getCell_Coord()
   * @model containment="true"
   * @generated
   */
  public Coordinate getCoord()
  {
    return coord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCoord(Coordinate newCoord, NotificationChain msgs)
  {
    Coordinate oldCoord = coord;
    coord = newCoord;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.CELL__COORD, oldCoord, newCoord);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Cell#getCoord <em>Coord</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCoord the new value of the '<em>Coord</em>' containment reference.
   * @see #getCoord()
   * @generated
   */
  public void setCoord(Coordinate newCoord)
  {
    if (newCoord != coord)
    {
      NotificationChain msgs = null;
      if (coord != null)
        msgs = coord.eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Pa19Package.CELL__COORD, null, msgs);
      if (newCoord != null)
        msgs = newCoord.eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Pa19Package.CELL__COORD, null, msgs);
      msgs = basicSetCoord(newCoord, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.CELL__COORD, newCoord, newCoord));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Creates a Cell instance from a character representation, coordinate, and termination type.
   * Algorithm:
   *   1. Determine the character type:
   *      - If c is the wall character, return a new Wall with the given coordinate.
   *      - If c is a termination arrow character, determine its direction and create a TerminationCell with the given coordinate, direction, and terminationType.
   *      - Otherwise, treat c as a pipe shape character and create a FillableCell with a Pipe of that shape (unfilled) and the given coordinate.
   *   2. Return the created cell.
   * Related Features: Coordinate attribute of Cell.
   * Related Classes: Wall, TerminationCell, FillableCell, Pipe, Coordinate, Direction, TerminationType.
   * Input:
   *   - c: A character representing the cell type. Must be one of the valid characters defined in PipePatterns.
   *   - coord: The coordinate where this cell is located in the map. Must be within map bounds.
   *   - terminationType: Specifies whether this termination is a SOURCE or SINK. Only used if c is a termination arrow.
   * Output: A new Cell object (Wall, TerminationCell, or FillableCell).
   * Pre-condition:
   *   - The character c must be a valid representation as defined in PipePatterns.
   *   - coord must be a valid coordinate (row and col >= 1).
   *   - terminationType must be provided if c is a termination arrow.
   * Post-condition:
   *   - The returned Cell has its coord attribute set to the given coordinate.
   *   - For TerminationCell, its type is set to the given terminationType.
   *   - For FillableCell, its pipe is unfilled.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Cell fromChar(final char c, final Coordinate coord, final TerminationType terminationType)
  {
    // Check if character is wall
    if (c == PipePatterns.WALL_CHAR) {
      Wall wall = Pa19Factory.eINSTANCE.createWall();
      wall.setCoord(coord);
      return wall;
    }
    
    // Check if character is a termination arrow
    if (PipePatterns.isTerminationArrow(c)) {
      Direction direction = PipePatterns.getDirectionFromArrow(c);
      TerminationCell terminationCell = Pa19Factory.eINSTANCE.createTerminationCell();
      terminationCell.setCoord(coord);
      terminationCell.setDirection(direction);
      terminationCell.setType(terminationType);
      return terminationCell;
    }
    
    // Otherwise treat as pipe shape character
    FillableCell fillableCell = Pa19Factory.eINSTANCE.createFillableCell();
    Pipe pipe = Pa19Factory.eINSTANCE.createPipe();
    pipe.setShape(PipePatterns.getShapeFromChar(c));
    pipe.setFilled(false);
    fillableCell.setPipe(pipe);
    fillableCell.setCoord(coord);
    return fillableCell;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Abstract method to return a single character representation of the map element.
   * Algorithm: (Abstract, implemented by subclasses)
   * Related Features: None (abstract).
   * Related Classes: Cell, Pipe.
   * Input: None.
   * Output: A character representing the element.
   * Pre-condition: None.
   * Post-condition: None.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public char toSingleChar()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.CELL__COORD:
        return basicSetCoord(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.CELL__COORD:
        return getCoord();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.CELL__COORD:
        setCoord((Coordinate)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.CELL__COORD:
        setCoord((Coordinate)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.CELL__COORD:
        return coord != null;
    }
    return super.eIsSet(featureID);
  }

} // Cell
