/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Coordinate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.Coordinate#getRow <em>Row</em>}</li>
 *   <li>{@link edu.pa19.Coordinate#getCol <em>Col</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getCoordinate()
 * @model kind="class"
 * @generated
 */
public class Coordinate extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected static final int ROW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected int row = ROW_EDEFAULT;

  /**
   * The default value of the '{@link #getCol() <em>Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCol()
   * @generated
   * @ordered
   */
  protected static final int COL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCol() <em>Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCol()
   * @generated
   * @ordered
   */
  protected int col = COL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Coordinate()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.COORDINATE;
  }

  /**
   * Returns the value of the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' attribute.
   * @see edu.pa19.Pa19Package#getCoordinate_Row()
   * @model changeable="false"
   * @generated
   */
  public int getRow()
  {
    return row;
  }

  /**
   * Returns the value of the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' attribute.
   * @see edu.pa19.Pa19Package#getCoordinate_Col()
   * @model changeable="false"
   * @generated
   */
  public int getCol()
  {
    return col;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns a new Coordinate that is the vector sum of this coordinate and another.
   * Algorithm:
   *   1. Return a new Coordinate with row = this.row + other.row, col = this.col + other.col.
   * Related Features: row, col.
   * Related Classes: Coordinate.
   * Input:
   *   - other: Another Coordinate to add.
   * Output: A new Coordinate representing the sum.
   * Pre-condition: None.
   * Post-condition: The original coordinates are unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public Coordinate add(final Coordinate other)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.COORDINATE__ROW:
        return getRow();
      case Pa19Package.COORDINATE__COL:
        return getCol();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.COORDINATE__ROW:
        return row != ROW_EDEFAULT;
      case Pa19Package.COORDINATE__COL:
        return col != COL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (row: ");
    result.append(row);
    result.append(", col: ");
    result.append(col);
    result.append(')');
    return result.toString();
  }

} // Coordinate
