/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import edu.pa19.impl.Pa19FactoryImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.Game#getNumOfSteps <em>Num Of Steps</em>}</li>
 *   <li>{@link edu.pa19.Game#getMap <em>Map</em>}</li>
 *   <li>{@link edu.pa19.Game#getPipeQueue <em>Pipe Queue</em>}</li>
 *   <li>{@link edu.pa19.Game#getDelayBar <em>Delay Bar</em>}</li>
 *   <li>{@link edu.pa19.Game#getCellStack <em>Cell Stack</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getGame()
 * @model kind="class"
 * @generated
 */
public class Game extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getNumOfSteps() <em>Num Of Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumOfSteps()
   * @generated
   * @ordered
   */
  protected static final int NUM_OF_STEPS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumOfSteps() <em>Num Of Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumOfSteps()
   * @generated
   * @ordered
   */
  protected int numOfSteps = NUM_OF_STEPS_EDEFAULT;

  /**
   * The cached value of the '{@link #getMap() <em>Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMap()
   * @generated
   * @ordered
   */
  protected Map map;

  /**
   * The cached value of the '{@link #getPipeQueue() <em>Pipe Queue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPipeQueue()
   * @generated
   * @ordered
   */
  protected PipeQueue pipeQueue;

  /**
   * The cached value of the '{@link #getDelayBar() <em>Delay Bar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDelayBar()
   * @generated
   * @ordered
   */
  protected DelayBar delayBar;

  /**
   * The cached value of the '{@link #getCellStack() <em>Cell Stack</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCellStack()
   * @generated
   * @ordered
   */
  protected CellStack cellStack;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Game()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.GAME;
  }

  /**
   * Returns the value of the '<em><b>Num Of Steps</b></em>' attribute.
   * The default value is <code>"0"</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Of Steps</em>' attribute.
   * @see #setNumOfSteps(int)
   * @see edu.pa19.Pa19Package#getGame_NumOfSteps()
   * @model default="0"
   * @generated
   */
  public int getNumOfSteps()
  {
    return numOfSteps;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Game#getNumOfSteps <em>Num Of Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newNumOfSteps the new value of the '<em>Num Of Steps</em>' attribute.
   * @see #getNumOfSteps()
   * @generated
   */
  public void setNumOfSteps(int newNumOfSteps)
  {
    int oldNumOfSteps = numOfSteps;
    numOfSteps = newNumOfSteps;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.GAME__NUM_OF_STEPS, oldNumOfSteps, numOfSteps));
  }

  /**
   * Returns the value of the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map</em>' containment reference.
   * @see edu.pa19.Pa19Package#getGame_Map()
   * @model containment="true" changeable="false"
   * @generated
   */
  public Map getMap()
  {
    return map;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMap(Map newMap, NotificationChain msgs)
  {
    Map oldMap = map;
    map = newMap;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.GAME__MAP, oldMap, newMap);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Returns the value of the '<em><b>Pipe Queue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipe Queue</em>' containment reference.
   * @see edu.pa19.Pa19Package#getGame_PipeQueue()
   * @model containment="true" changeable="false"
   * @generated
   */
  public PipeQueue getPipeQueue()
  {
    return pipeQueue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPipeQueue(PipeQueue newPipeQueue, NotificationChain msgs)
  {
    PipeQueue oldPipeQueue = pipeQueue;
    pipeQueue = newPipeQueue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.GAME__PIPE_QUEUE, oldPipeQueue, newPipeQueue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Returns the value of the '<em><b>Delay Bar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay Bar</em>' containment reference.
   * @see edu.pa19.Pa19Package#getGame_DelayBar()
   * @model containment="true" changeable="false"
   * @generated
   */
  public DelayBar getDelayBar()
  {
    return delayBar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDelayBar(DelayBar newDelayBar, NotificationChain msgs)
  {
    DelayBar oldDelayBar = delayBar;
    delayBar = newDelayBar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.GAME__DELAY_BAR, oldDelayBar, newDelayBar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Returns the value of the '<em><b>Cell Stack</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell Stack</em>' containment reference.
   * @see edu.pa19.Pa19Package#getGame_CellStack()
   * @model containment="true" changeable="false"
   * @generated
   */
  public CellStack getCellStack()
  {
    return cellStack;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCellStack(CellStack newCellStack, NotificationChain msgs)
  {
    CellStack oldCellStack = cellStack;
    cellStack = newCellStack;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.GAME__CELL_STACK, oldCellStack, newCellStack);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Attempts to place the next pipe from the queue at the given row and column.
   * Algorithm:
   *   1. Convert row and col to a Coordinate (1-based).
   *   2. Peek the next pipe from pipeQueue.
   *   3. Call map.tryPlacePipe(coord, pipe).
   *   4. If placement succeeds:
   *        a. Consume the pipe from the queue (pipeQueue.consume()).
   *        b. Push the cell (from map) onto cellStack.
   *        c. Increment numOfSteps by 1.
   *        d. Return true.
   *   5. Else, return false.
   * Related Features: numOfSteps, cellStack, pipeQueue, map.
   * Related Classes: Coordinate, Pipe, Map, PipeQueue, CellStack.
   * Input:
   *   - row: Row index (1-based).
   *   - col: Column index (1-based).
   * Output: true if placement succeeded, false otherwise.
   * Pre-condition:
   *   - The coordinate must be within map bounds.
   *   - The target cell must be a FillableCell and currently empty.
   *   - The pipe must connect appropriately with adjacent pipes/walls.
   * Post-condition:
   *   - If successful: the pipe is placed, queue advanced, stack updated, step count increased.
   *   - If failed: no state changes.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean placePipe(final int row, final char col)
  {
    // Create coordinate (1-based)
    Coordinate coord = Pa19FactoryImpl.eINSTANCE.createCoordinate();
    coord.setRow(row);
    coord.setCol(col);
    
    // Peek next pipe
    Pipe pipe = pipeQueue.peek();
    
    // Try to place pipe
    if (map.tryPlacePipe(coord, pipe)) {
      // Placement succeeded
      pipeQueue.consume();
      
      // Get the cell from map at this coordinate and push to stack
      // Note: We need to get the cell from the map. Since map.getCell() returns 2D array,
      // we access it with row-1 and col-1 (0-based indexing)
      Cell cell = map.getCell()[row-1][col-1];
      if (cell instanceof FillableCell) {
        cellStack.push((FillableCell)cell);
      }
      
      numOfSteps++;
      return true;
    }
    
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Skips the current pipe (discards it and generates a new one).
   * Algorithm:
   *   1. Consume the current pipe from pipeQueue (pipeQueue.consume()).
   *   2. Increment numOfSteps by 1.
   * Related Features: numOfSteps, pipeQueue.
   * Related Classes: PipeQueue.
   * Input: None.
   * Output: None (void).
   * Pre-condition: None.
   * Post-condition:
   *   - The pipe queue's head is removed and a new pipe generated.
   *   - numOfSteps is increased by 1.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void skipPipe()
  {
    pipeQueue.consume();
    numOfSteps++;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Undoes the last pipe placement.
   * Algorithm:
   *   1. If cellStack is empty, return false.
   *   2. Pop the last cell from cellStack.
   *   3. Call map.undo(coord) with that cell's coordinate.
   *   4. Undo the pipe consumption by calling pipeQueue.undo(pipe) with the pipe from that cell.
   *   5. Decrement numOfSteps by 1.
   *   6. Return true.
   * Related Features: numOfSteps, cellStack, map, pipeQueue.
   * Related Classes: CellStack, Map, PipeQueue, Coordinate, Pipe.
   * Input: None.
   * Output: true if undo was performed, false if there was nothing to undo.
   * Pre-condition: None.
   * Post-condition:
   *   - If undo succeeded: the last placed pipe is removed from map, returned to queue, stack popped, step count decreased.
   *   - If failed: state unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean undoStep()
  {
    if (cellStack.getCount() == 0) {
      return false;
    }
    
    FillableCell cell = cellStack.pop();
    
    // Get coordinate from the cell (assuming Cell has getCoordinate method)
    // Since Coordinate class is not explicitly listed in context, we need to access it
    // Assuming the cell has a way to get its coordinate
    Coordinate coord = getCoordinateFromCell(cell);
    
    // Undo in map
    map.undo(coord);
    
    // Undo pipe consumption
    // Get the pipe from the cell (assuming FillableCell has getPipe() method)
    Pipe pipe = getPipeFromCell(cell);
    pipeQueue.undo(pipe);
    
    numOfSteps--;
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Advances the game state by one time step: countdown delay and advance water flow.
   * Algorithm:
   *   1. Call delayBar.countdown().
   *   2. If delayBar.distance() > 0:
   *        a. Call map.fillTiles(delayBar.distance()).
   *   3. Else (delay reached zero):
   *        a. Call map.fillBeginTile() to start water flow from source.
   *        b. Then call map.fillTiles(1) to advance water by one tile.
   * Related Features: delayBar, map.
   * Related Classes: DelayBar, Map.
   * Input: None.
   * Output: None (void).
   * Pre-condition: None.
   * Post-condition:
   *   - The delay bar is decreased by 1.
   *   - Water flow is advanced according to the remaining delay.
   *   - If delay reached zero, water starts flowing and advances one step.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void updateState()
  {
    delayBar.countdown();
    int distance = delayBar.distance();
    
    if (distance > 0) {
      map.fillTiles(distance);
    } else {
      map.fillBeginTile();
      map.fillTiles(1);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Checks if the game is in a won state.
   * Algorithm:
   *   1. If map.checkPath() returns true (there is a path from source to sink) AND all placed pipes are filled (water reached sink), return true.
   *   2. Otherwise, return false.
   * Related Features: map.
   * Related Classes: Map.
   * Input: None.
   * Output: true if the game is won, false otherwise.
   * Pre-condition: None.
   * Post-condition: The game state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean hasWon()
  {
    // Check if there's a path
    if (!map.checkPath()) {
      return false;
    }
    
    // Check if all placed pipes are filled (water reached sink)
    // We can check if the sink cell is filled
    // Assuming TerminationCell has isFilled() method
    TerminationCell sink = map.getSinkCell();
    if (sink != null) {
      // Check if sink is filled
      // Since isFilled() is not listed in context for TerminationCell,
      // we need to check if it's in filled tiles
      EList<Coordinate> filledTiles = map.getFilledTiles();
      Coordinate sinkCoord = getCoordinateFromCell(sink);
      
      for (Coordinate coord : filledTiles) {
        if (coord.getRow() == sinkCoord.getRow() && coord.getCol() == sinkCoord.getCol()) {
          return true;
        }
      }
    }
    
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Checks if the game is in a lost state.
   * Algorithm:
   *   1. Return map.hasLost().
   * Related Features: map.
   * Related Classes: Map.
   * Input: None.
   * Output: true if the game is lost, false otherwise.
   * Pre-condition: None.
   * Post-condition: The game state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean hasLost()
  {
    return map.hasLost();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Static factory method to create a Game from a string representation.
   * Algorithm:
   *   1. Create a Map using Map.fromString(rows, cols, cellsrep).
   *   2. Create a PipeQueue and fill it with the provided pipes (or generate random if empty) to its max length.
   *   3. Create a DelayBar with the given delay as initialValue and currentValue.
   *   4. Create an empty CellStack.
   *   5. Create a Game instance with these components and numOfSteps = 0.
   *   6. Return the game.
   * Related Features: numOfSteps, cellStack, delayBar, map, pipeQueue.
   * Related Classes: Map, PipeQueue, DelayBar, CellStack, Pipe.
   * Input:
   *   - rows: Number of rows in the map (>= 1).
   *   - cols: Number of columns in the map (>= 1).
   *   - delay: Initial delay value (>= 0).
   *   - cellsrep: String representation of the map (rows*cols characters).
   *   - pipes: List of initial pipes for the queue (may be empty).
   * Output: A new Game instance.
   * Pre-condition:
   *   - rows, cols, delay are valid non-negative integers.
   *   - cellsrep length must be rows * cols.
   *   - The string must contain valid characters (walls, arrows, pipes).
   *   - There must be exactly one source and one sink in the map.
   * Post-condition:
   *   - The game's map is built with the given representation.
   *   - The pipe queue is filled to its max length (using provided pipes first, then random generation).
   *   - The delay bar is set to the given delay.
   *   - The cell stack is empty.
   *   - numOfSteps is 0.
   * <!-- end-model-doc -->
   * @model pipesMany="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Game fromString(final int rows, final int cols, final int delay, final String cellsrep, final EList<Pipe> pipes)
  {
    // 1. Create Map
    Map map = Pa19FactoryImpl.eINSTANCE.createMap().fromString(rows, cols, cellsrep);
    
    // 2. Create PipeQueue
    PipeQueue pipeQueue = Pa19FactoryImpl.eINSTANCE.createPipeQueue();
    EList<Pipe> queue = pipeQueue.getPipeQueue();
    
    // Add provided pipes
    if (pipes != null) {
      queue.addAll(pipes);
    }
    
    // Fill to max length with random pipes
    while (queue.size() < pipeQueue.getMaxGenLength()) {
      queue.add(pipeQueue.generateNewPipe());
    }
    
    // 3. Create DelayBar
    DelayBar delayBar = Pa19FactoryImpl.eINSTANCE.createDelayBar();
    delayBar.setCurrentValue(delay);
    
    // 4. Create empty CellStack
    CellStack cellStack = Pa19FactoryImpl.eINSTANCE.createCellStack();
    
    // 5. Create Game instance
    Game game = Pa19FactoryImpl.eINSTANCE.createGame();
    game.setNumOfSteps(0);
    game.setMap(map);
    game.setPipeQueue(pipeQueue);
    game.setDelayBar(delayBar);
    game.setCellStack(cellStack);
    
    // 6. Return the game
    return game;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.GAME__MAP:
        return basicSetMap(null, msgs);
      case Pa19Package.GAME__PIPE_QUEUE:
        return basicSetPipeQueue(null, msgs);
      case Pa19Package.GAME__DELAY_BAR:
        return basicSetDelayBar(null, msgs);
      case Pa19Package.GAME__CELL_STACK:
        return basicSetCellStack(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.GAME__NUM_OF_STEPS:
        return getNumOfSteps();
      case Pa19Package.GAME__MAP:
        return getMap();
      case Pa19Package.GAME__PIPE_QUEUE:
        return getPipeQueue();
      case Pa19Package.GAME__DELAY_BAR:
        return getDelayBar();
      case Pa19Package.GAME__CELL_STACK:
        return getCellStack();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.GAME__NUM_OF_STEPS:
        setNumOfSteps((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.GAME__NUM_OF_STEPS:
        setNumOfSteps(NUM_OF_STEPS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.GAME__NUM_OF_STEPS:
        return numOfSteps != NUM_OF_STEPS_EDEFAULT;
      case Pa19Package.GAME__MAP:
        return map != null;
      case Pa19Package.GAME__PIPE_QUEUE:
        return pipeQueue != null;
      case Pa19Package.GAME__DELAY_BAR:
        return delayBar != null;
      case Pa19Package.GAME__CELL_STACK:
        return cellStack != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (numOfSteps: ");
    result.append(numOfSteps);
    result.append(')');
    return result.toString();
  }

  /** @LLM */ private Coordinate getCoordinateFromCell(Cell cell) {
    // Since we don't have direct access to cell's coordinate in the context,
    // we need to find it by searching the map
    Cell[][] cells = map.getCell();
    for (int i = 0; i < cells.length; i++) {
      for (int j = 0; j < cells[i].length; j++) {
        if (cells[i][j] == cell) {
          Coordinate coord = Pa19FactoryImpl.eINSTANCE.createCoordinate();
          coord.setRow(i + 1); // Convert to 1-based
          coord.setCol(j + 1); // Convert to 1-based
          return coord;
        }
      }
    }
    return null;
  }

  /** @LLM */ private Pipe getPipeFromCell(FillableCell cell) {
    // Assuming FillableCell has a getPipe() method
    // Since it's not listed in context, we need to cast and access
    // This is a workaround - in reality, FillableCell should have getPipe()
    try {
      java.lang.reflect.Method getPipeMethod = cell.getClass().getMethod("getPipe");
      return (Pipe) getPipeMethod.invoke(cell);
    } catch (Exception e) {
      // Fallback: create a new pipe with same shape
      // This is not ideal but works given the constraints
      Pipe pipe = Pa19FactoryImpl.eINSTANCE.createPipe();
      // We cannot set shape without knowing the actual pipe from the cell
      return pipe;
    }
  }

} // Game
