/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.Map#getRows <em>Rows</em>}</li>
 *   <li>{@link edu.pa19.Map#getCols <em>Cols</em>}</li>
 *   <li>{@link edu.pa19.Map#getPrevFilledTiles <em>Prev Filled Tiles</em>}</li>
 *   <li>{@link edu.pa19.Map#getPrevFilledDistance <em>Prev Filled Distance</em>}</li>
 *   <li>{@link edu.pa19.Map#getSourceCell <em>Source Cell</em>}</li>
 *   <li>{@link edu.pa19.Map#getSinkCell <em>Sink Cell</em>}</li>
 *   <li>{@link edu.pa19.Map#getFilledTiles <em>Filled Tiles</em>}</li>
 *   <li>{@link edu.pa19.Map#getCells <em>Cells</em>}</li>
 *   <li>{@link edu.pa19.Map#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getMap()
 * @model kind="class"
 * @generated
 */
public class Map extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getRows() <em>Rows</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRows()
   * @generated
   * @ordered
   */
  protected static final int ROWS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRows() <em>Rows</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRows()
   * @generated
   * @ordered
   */
  protected int rows = ROWS_EDEFAULT;

  /**
   * The default value of the '{@link #getCols() <em>Cols</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCols()
   * @generated
   * @ordered
   */
  protected static final int COLS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCols() <em>Cols</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCols()
   * @generated
   * @ordered
   */
  protected int cols = COLS_EDEFAULT;

  /**
   * The default value of the '{@link #getPrevFilledTiles() <em>Prev Filled Tiles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevFilledTiles()
   * @generated
   * @ordered
   */
  protected static final int PREV_FILLED_TILES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPrevFilledTiles() <em>Prev Filled Tiles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevFilledTiles()
   * @generated
   * @ordered
   */
  protected int prevFilledTiles = PREV_FILLED_TILES_EDEFAULT;

  /**
   * The default value of the '{@link #getPrevFilledDistance() <em>Prev Filled Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevFilledDistance()
   * @generated
   * @ordered
   */
  protected static final Integer PREV_FILLED_DISTANCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrevFilledDistance() <em>Prev Filled Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrevFilledDistance()
   * @generated
   * @ordered
   */
  protected Integer prevFilledDistance = PREV_FILLED_DISTANCE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSourceCell() <em>Source Cell</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceCell()
   * @generated
   * @ordered
   */
  protected TerminationCell sourceCell;

  /**
   * The cached value of the '{@link #getSinkCell() <em>Sink Cell</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSinkCell()
   * @generated
   * @ordered
   */
  protected TerminationCell sinkCell;

  /**
   * The cached value of the '{@link #getFilledTiles() <em>Filled Tiles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilledTiles()
   * @generated
   * @ordered
   */
  protected EList<Coordinate> filledTiles;

  /**
   * The cached value of the '{@link #getCells() <em>Cells</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCells()
   * @generated
   * @ordered
   */
  protected EList<Cell> cells;

  /**
   * The default value of the '{@link #getCell() <em>Cell</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCell()
   * @generated
   * @ordered
   */
  protected static final Cell[][] CELL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCell() <em>Cell</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCell()
   * @generated
   * @ordered
   */
  protected Cell[][] cell = CELL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Map()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.MAP;
  }

  /**
   * Returns the value of the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rows</em>' attribute.
   * @see edu.pa19.Pa19Package#getMap_Rows()
   * @model required="true" changeable="false"
   * @generated
   */
  public int getRows()
  {
    return rows;
  }

  /**
   * Returns the value of the '<em><b>Cols</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cols</em>' attribute.
   * @see edu.pa19.Pa19Package#getMap_Cols()
   * @model required="true" changeable="false"
   * @generated
   */
  public int getCols()
  {
    return cols;
  }

  /**
   * Returns the value of the '<em><b>Prev Filled Tiles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prev Filled Tiles</em>' attribute.
   * @see edu.pa19.Pa19Package#getMap_PrevFilledTiles()
   * @model transient="true" changeable="false"
   * @generated
   */
  public int getPrevFilledTiles()
  {
    return prevFilledTiles;
  }

  /**
   * Returns the value of the '<em><b>Prev Filled Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prev Filled Distance</em>' attribute.
   * @see edu.pa19.Pa19Package#getMap_PrevFilledDistance()
   * @model transient="true" changeable="false"
   * @generated
   */
  public Integer getPrevFilledDistance()
  {
    return prevFilledDistance;
  }

  /**
   * Returns the value of the '<em><b>Source Cell</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Cell</em>' reference.
   * @see #setSourceCell(TerminationCell)
   * @see edu.pa19.Pa19Package#getMap_SourceCell()
   * @model required="true"
   * @generated
   */
  public TerminationCell getSourceCell()
  {
    if (sourceCell != null && sourceCell.eIsProxy())
    {
      InternalEObject oldSourceCell = sourceCell;
      sourceCell = (TerminationCell)eResolveProxy(oldSourceCell);
      if (sourceCell != oldSourceCell)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Pa19Package.MAP__SOURCE_CELL, oldSourceCell, sourceCell));
      }
    }
    return sourceCell;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TerminationCell basicGetSourceCell()
  {
    return sourceCell;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Map#getSourceCell <em>Source Cell</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newSourceCell the new value of the '<em>Source Cell</em>' reference.
   * @see #getSourceCell()
   * @generated
   */
  public void setSourceCell(TerminationCell newSourceCell)
  {
    TerminationCell oldSourceCell = sourceCell;
    sourceCell = newSourceCell;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.MAP__SOURCE_CELL, oldSourceCell, sourceCell));
  }

  /**
   * Returns the value of the '<em><b>Sink Cell</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sink Cell</em>' reference.
   * @see #setSinkCell(TerminationCell)
   * @see edu.pa19.Pa19Package#getMap_SinkCell()
   * @model required="true"
   * @generated
   */
  public TerminationCell getSinkCell()
  {
    if (sinkCell != null && sinkCell.eIsProxy())
    {
      InternalEObject oldSinkCell = sinkCell;
      sinkCell = (TerminationCell)eResolveProxy(oldSinkCell);
      if (sinkCell != oldSinkCell)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Pa19Package.MAP__SINK_CELL, oldSinkCell, sinkCell));
      }
    }
    return sinkCell;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TerminationCell basicGetSinkCell()
  {
    return sinkCell;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Map#getSinkCell <em>Sink Cell</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newSinkCell the new value of the '<em>Sink Cell</em>' reference.
   * @see #getSinkCell()
   * @generated
   */
  public void setSinkCell(TerminationCell newSinkCell)
  {
    TerminationCell oldSinkCell = sinkCell;
    sinkCell = newSinkCell;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.MAP__SINK_CELL, oldSinkCell, sinkCell));
  }

  /**
   * Returns the value of the '<em><b>Filled Tiles</b></em>' containment reference list.
   * The list contents are of type {@link edu.pa19.Coordinate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filled Tiles</em>' containment reference list.
   * @see edu.pa19.Pa19Package#getMap_FilledTiles()
   * @model containment="true" transient="true"
   * @generated
   */
  public EList<Coordinate> getFilledTiles()
  {
    if (filledTiles == null)
    {
      filledTiles = new EObjectContainmentEList<Coordinate>(Coordinate.class, this, Pa19Package.MAP__FILLED_TILES);
    }
    return filledTiles;
  }

  /**
   * Returns the value of the '<em><b>Cells</b></em>' containment reference list.
   * The list contents are of type {@link edu.pa19.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cells</em>' containment reference list.
   * @see edu.pa19.Pa19Package#getMap_Cells()
   * @model containment="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen requirement='{\n  \"feature\": \"cells\",\n  \"pattern\": \"Flattened2DArray\",\n  \"logic\": {\n    \"indexing\": \"Row-Major Order\",\n    \"formula\": \"index = row * cols + col\",\n    \"access_methods\": [\n      {\n        \"name\": \"getCell\",\n        \"params\": [\"int row\", \"int col\"],\n        \"body\": \"return getCells().get(row * getCols() + col);\"\n      },\n      {\n        \"name\": \"setCell\",\n        \"params\": [\"int row\", \"int col\", \"Cell cell\"],\n        \"body\": \"getCells().set(row * getCols() + col, cell);\"\n      }\n    ]\n  },\n  \"constraints\": [\n    \"Total size must be rows * cols\",\n    \"Boundary check: 0 &lt;= row &lt; rows &amp;&amp; 0 &lt;= col &lt; cols\"\n  ]\n}'"
   * @generated
   */
  public EList<Cell> getCells()
  {
    if (cells == null)
    {
      cells = new EObjectContainmentEList<Cell>(Cell.class, this, Pa19Package.MAP__CELLS);
    }
    return cells;
  }

  /**
   * Returns the value of the '<em><b>Cell</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' attribute.
   * @see #setCell(Cell[][])
   * @see edu.pa19.Pa19Package#getMap_Cell()
   * @model dataType="edu.pa19.cellarray"
   * @generated
   */
  public Cell[][] getCell()
  {
    return cell;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Map#getCell <em>Cell</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCell the new value of the '<em>Cell</em>' attribute.
   * @see #getCell()
   * @generated
   */
  public void setCell(Cell[][] newCell)
  {
    Cell[][] oldCell = cell;
    cell = newCell;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.MAP__CELL, oldCell, cell));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Attempts to place a pipe at the given coordinate.
   * Algorithm:
   *   1. Check if the coordinate is within bounds and the cell is a FillableCell and currently empty (no pipe).
   *   2. Check if the pipe connections are compatible with adjacent cells (walls, other pipes, terminations):
   *        a. For each direction the pipe connects, the neighbor in that direction must either:
   *            - Be a wall or out of bounds: invalid.
   *            - Be a termination cell: must point inward/outward appropriately.
   *            - Be a FillableCell with a pipe: that pipe must have a connection in the opposite direction.
   *   3. If all checks pass:
   *        a. Set the cell's pipe to the given pipe.
   *        b. Return true.
   *   4. Else, return false.
   * Related Features: cells.
   * Related Classes: FillableCell, Pipe, Wall, TerminationCell, Direction, Coordinate.
   * Input:
   *   - coord: Coordinate to place the pipe.
   *   - pipe: The pipe to place.
   * Output: true if placement succeeded, false otherwise.
   * Pre-condition:
   *   - coord must be within map bounds.
   *   - The target cell must be a FillableCell.
   * Post-condition:
   *   - If successful: the pipe is placed in the cell.
   *   - If failed: no state changes.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public boolean tryPlacePipe(final Coordinate coord, final Pipe pipe)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a pipe from the given coordinate (for undo).
   * Algorithm:
   *   1. Get the cell at the coordinate (must be a FillableCell).
   *   2. Set its pipe to null.
   * Related Features: cells.
   * Related Classes: FillableCell.
   * Input:
   *   - coord: Coordinate of the cell to undo.
   * Output: None (void).
   * Pre-condition:
   *   - The coordinate must be within bounds.
   *   - The cell at coord must be a FillableCell and have a pipe.
   * Post-condition: The pipe is removed from the cell.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void undo(final Coordinate coord)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Initiates water flow by marking the source cell as filled.
   * Algorithm:
   *   1. Set sourceCell.isFilled = true.
   *   2. Add sourceCell.coord to filledTiles list.
   *   3. Reset prevFilledDistance to 0.
   *   4. Reset prevFilledTiles to 0.
   * Related Features: sourceCell, filledTiles, prevFilledDistance, prevFilledTiles.
   * Related Classes: TerminationCell, Coordinate.
   * Input: None.
   * Output: None (void).
   * Pre-condition: The source cell must not already be filled.
   * Post-condition: The source cell is marked filled and its coordinate is recorded.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void fillBeginTile()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Expands water flow from already filled tiles by a given distance.
   * Algorithm:
   *   1. For distance d from prevFilledDistance+1 to prevFilledDistance+distance:
   *        a. For each tile in filledTiles (starting from index prevFilledTiles to end):
   *            i. For each direction that the tile's pipe (or termination) connects:
   *                - Compute neighbor coordinate.
   *                - If neighbor is within bounds and has a pipe that connects back to current tile:
   *                    * Mark neighbor as filled (set pipe.filled = true or termination.isFilled = true).
   *                    * Add neighbor coordinate to filledTiles.
   *        b. Update prevFilledTiles to the size of filledTiles before this iteration.
   *   2. Update prevFilledDistance by adding distance.
   * Related Features: filledTiles, prevFilledDistance, prevFilledTiles, cells.
   * Related Classes: FillableCell, TerminationCell, Pipe, Direction, Coordinate.
   * Input:
   *   - distance: Number of steps to expand flow (>= 0).
   * Output: None (void).
   * Pre-condition: Water flow must have been started (source filled).
   * Post-condition: Water expands along connected pipes up to the given distance, marking tiles as filled.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void fillTiles(final int distance)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Checks if there exists a connected path from source to sink using the placed pipes.
   * Algorithm:
   *   1. Perform a graph search (BFS/DFS) starting from the source cell, following pipe connections.
   *   2. Only traverse through cells that have a pipe and are connected appropriately.
   *   3. If the sink cell is reached, return true.
   *   4. Otherwise, return false.
   * Related Features: sourceCell, sinkCell, cells.
   * Related Classes: TerminationCell, FillableCell, Pipe, Direction.
   * Input: None.
   * Output: true if a path exists, false otherwise.
   * Pre-condition: None.
   * Post-condition: The map state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public boolean checkPath()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Checks if the game is in a lost state (no possible path from source to sink).
   * Algorithm:
   *   1. If checkPath() returns false, return true.
   *   2. Otherwise, return false.
   * Related Features: checkPath.
   * Related Classes: None.
   * Input: None.
   * Output: true if there is no path (lost), false otherwise.
   * Pre-condition: None.
   * Post-condition: The map state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public boolean hasLost()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Displays the current map state (for debugging or UI).
   * Algorithm:
   *   1. For each row and column, get the cell and call its toSingleChar().
   *   2. Print the characters row by row.
   * Related Features: cells, rows, cols.
   * Related Classes: Cell.
   * Input: None.
   * Output: None (void). Output is printed to console or UI.
   * Pre-condition: None.
   * Post-condition: The map state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public void display()
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Static factory method to create a Map from a string representation.
   * Algorithm:
   *   1. Create a 2D array of Cell of size rows x cols.
   *   2. For each character in rep (row-major order):
   *        a. Determine its coordinate (row = index/cols +1, col = index%cols +1).
   *        b. Determine termination type: if it's the source arrow, type=SOURCE; if sink arrow, type=SINK.
   *        c. Call Cell.fromChar(c, coord, terminationType) to create the cell.
   *        d. Store the cell in the array and also in a flat list.
   *        e. If it's a termination cell, record it as sourceCell or sinkCell accordingly.
   *   3. Return a Map with the created cells, rows, cols, and empty filledTiles.
   * Related Features: cells, rows, cols, sourceCell, sinkCell.
   * Related Classes: Cell, TerminationCell, Wall, FillableCell, Coordinate, TerminationType.
   * Input:
   *   - r: Number of rows (>=1).
   *   - c: Number of columns (>=1).
   *   - rep: String of length r*c with valid map characters.
   * Output: A new Map instance.
   * Pre-condition:
   *   - rep must contain exactly one source and one sink.
   *   - The map must be surrounded by walls (border cells must be walls or terminations).
   * Post-condition:
   *   - The map's cells are initialized according to the string.
   *   - sourceCell and sinkCell are set.
   *   - filledTiles is empty.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  public Map fromString(final int r, final int c, final String rep)
  {
    // TODO: Please generate a body of this unimplemented method based on the docstring
    // TODO: Replace the current body with the generated body 
    // TODO: Ensure that you mark it @generated NOT after code completion
    throw new UnsupportedOperationException();
    
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.MAP__FILLED_TILES:
        return ((InternalEList<?>)getFilledTiles()).basicRemove(otherEnd, msgs);
      case Pa19Package.MAP__CELLS:
        return ((InternalEList<?>)getCells()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.MAP__ROWS:
        return getRows();
      case Pa19Package.MAP__COLS:
        return getCols();
      case Pa19Package.MAP__PREV_FILLED_TILES:
        return getPrevFilledTiles();
      case Pa19Package.MAP__PREV_FILLED_DISTANCE:
        return getPrevFilledDistance();
      case Pa19Package.MAP__SOURCE_CELL:
        if (resolve) return getSourceCell();
        return basicGetSourceCell();
      case Pa19Package.MAP__SINK_CELL:
        if (resolve) return getSinkCell();
        return basicGetSinkCell();
      case Pa19Package.MAP__FILLED_TILES:
        return getFilledTiles();
      case Pa19Package.MAP__CELLS:
        return getCells();
      case Pa19Package.MAP__CELL:
        return getCell();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.MAP__SOURCE_CELL:
        setSourceCell((TerminationCell)newValue);
        return;
      case Pa19Package.MAP__SINK_CELL:
        setSinkCell((TerminationCell)newValue);
        return;
      case Pa19Package.MAP__FILLED_TILES:
        getFilledTiles().clear();
        getFilledTiles().addAll((Collection<? extends Coordinate>)newValue);
        return;
      case Pa19Package.MAP__CELLS:
        getCells().clear();
        getCells().addAll((Collection<? extends Cell>)newValue);
        return;
      case Pa19Package.MAP__CELL:
        setCell((Cell[][])newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.MAP__SOURCE_CELL:
        setSourceCell((TerminationCell)null);
        return;
      case Pa19Package.MAP__SINK_CELL:
        setSinkCell((TerminationCell)null);
        return;
      case Pa19Package.MAP__FILLED_TILES:
        getFilledTiles().clear();
        return;
      case Pa19Package.MAP__CELLS:
        getCells().clear();
        return;
      case Pa19Package.MAP__CELL:
        setCell(CELL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.MAP__ROWS:
        return rows != ROWS_EDEFAULT;
      case Pa19Package.MAP__COLS:
        return cols != COLS_EDEFAULT;
      case Pa19Package.MAP__PREV_FILLED_TILES:
        return prevFilledTiles != PREV_FILLED_TILES_EDEFAULT;
      case Pa19Package.MAP__PREV_FILLED_DISTANCE:
        return PREV_FILLED_DISTANCE_EDEFAULT == null ? prevFilledDistance != null : !PREV_FILLED_DISTANCE_EDEFAULT.equals(prevFilledDistance);
      case Pa19Package.MAP__SOURCE_CELL:
        return sourceCell != null;
      case Pa19Package.MAP__SINK_CELL:
        return sinkCell != null;
      case Pa19Package.MAP__FILLED_TILES:
        return filledTiles != null && !filledTiles.isEmpty();
      case Pa19Package.MAP__CELLS:
        return cells != null && !cells.isEmpty();
      case Pa19Package.MAP__CELL:
        return CELL_EDEFAULT == null ? cell != null : !CELL_EDEFAULT.equals(cell);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (rows: ");
    result.append(rows);
    result.append(", cols: ");
    result.append(cols);
    result.append(", prevFilledTiles: ");
    result.append(prevFilledTiles);
    result.append(", prevFilledDistance: ");
    result.append(prevFilledDistance);
    result.append(", cell: ");
    result.append(cell);
    result.append(')');
    return result.toString();
  }

} // Map
