/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.pa19.Pa19Package#getMapElement()
 * @model kind="class" interface="true" abstract="true"
 * @generated
 */
public interface MapElement extends EObject
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Abstract method to return a single character representation of the map element.
   * Algorithm: (Abstract, implemented by subclasses)
   * Related Features: None (abstract).
   * Related Classes: Cell, Pipe.
   * Input: None.
   * Output: A character representing the element.
   * Pre-condition: None.
   * Post-condition: None.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated
   */
  char toSingleChar();

} // MapElement
