/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.pa19.Pa19Factory
 * @model kind="package"
 *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen requirement='Overall/Domain\n\nConsole pipe-connection game: grid with outer walls, one source inside pointing inward, one sink on the border pointing outward. Player places pipes from a queue; after a delay, water flows along placed pipes.\nCoordinates are 1-based. Direction provides four directions plus opposite/offset; PipeShape defines connection directions; TerminationType distinguishes SOURCE vs SINK.\nFunctional requirements (for generated EOperations; coarse-grained)\n\nGame: operations to place a pipe, skip, undo, advance water flow, check win, check loss; convenience fromString constructor; maintain step count.\nMap: operations to place pipe (by coord or row/col), undo a cell, start filling from source, expand filling by distance, check path existence, check loss state; access cells in flattened list with row/col attributes.\nCell family: Cell.fromChar parses map chars to concrete cells; FillableCell holds an optional pipe and renders pipe or \'.\'; TerminationCell renders arrows by filled state and direction; Wall renders wall char.\nPipe: expose connection directions, char rendering by filled/unfilled, construct from short string code.\nPipeQueue: peek/consume/undo head pipe and auto-refill to fixed length with random shapes.\nDelayBar: countdown and report flow distance; optional display.\nCellStack: push/pop last placement, report undo count; optional display.\nExternal/tool classes (not generated; handwritten or reused)\n\nDeserializer: read rows/cols/delay, map chars, and optional default pipes from file/string; build Cell[][] and construct Game.\nPipePatterns: constants for wall, arrows, and each pipe shape in filled/unfilled states.\nStringUtils: simple repeat/padding utility for UI.\nMain (CLI): parse args (file or size), loop render/read input and drive Game; outside the model.'"
 * @generated
 */
public class Pa19Package extends EPackageImpl
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNAME = "pa19";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_URI = "http://www.example.org/pa19";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_PREFIX = "pa19";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final Pa19Package eINSTANCE = edu.pa19.Pa19Package.init();

  /**
   * The meta object id for the '{@link edu.pa19.Game <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Game
   * @see edu.pa19.Pa19Package#getGame()
   * @generated
   */
  public static final int GAME = 0;

  /**
   * The feature id for the '<em><b>Num Of Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME__NUM_OF_STEPS = 0;

  /**
   * The feature id for the '<em><b>Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME__MAP = 1;

  /**
   * The feature id for the '<em><b>Pipe Queue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME__PIPE_QUEUE = 2;

  /**
   * The feature id for the '<em><b>Delay Bar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME__DELAY_BAR = 3;

  /**
   * The feature id for the '<em><b>Cell Stack</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME__CELL_STACK = 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link edu.pa19.MapElement <em>Map Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.MapElement
   * @see edu.pa19.Pa19Package#getMapElement()
   * @generated
   */
  public static final int MAP_ELEMENT = 11;

  /**
   * The number of structural features of the '<em>Map Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.pa19.Cell <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Cell
   * @see edu.pa19.Pa19Package#getCell()
   * @generated
   */
  public static final int CELL = 1;

  /**
   * The feature id for the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CELL__COORD = MAP_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CELL_FEATURE_COUNT = MAP_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.pa19.FillableCell <em>Fillable Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.FillableCell
   * @see edu.pa19.Pa19Package#getFillableCell()
   * @generated
   */
  public static final int FILLABLE_CELL = 2;

  /**
   * The feature id for the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FILLABLE_CELL__COORD = CELL__COORD;

  /**
   * The feature id for the '<em><b>Pipe</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FILLABLE_CELL__PIPE = CELL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fillable Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FILLABLE_CELL_FEATURE_COUNT = CELL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.pa19.Wall <em>Wall</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Wall
   * @see edu.pa19.Pa19Package#getWall()
   * @generated
   */
  public static final int WALL = 3;

  /**
   * The feature id for the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int WALL__COORD = CELL__COORD;

  /**
   * The number of structural features of the '<em>Wall</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int WALL_FEATURE_COUNT = CELL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.pa19.TerminationCell <em>Termination Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.TerminationCell
   * @see edu.pa19.Pa19Package#getTerminationCell()
   * @generated
   */
  public static final int TERMINATION_CELL = 4;

  /**
   * The feature id for the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CELL__COORD = CELL__COORD;

  /**
   * The feature id for the '<em><b>Is Filled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CELL__IS_FILLED = CELL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Pointing To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CELL__POINTING_TO = CELL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CELL__TYPE = CELL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Termination Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CELL_FEATURE_COUNT = CELL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.pa19.Pipe <em>Pipe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Pipe
   * @see edu.pa19.Pa19Package#getPipe()
   * @generated
   */
  public static final int PIPE = 5;

  /**
   * The feature id for the '<em><b>Filled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE__FILLED = MAP_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Shape</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE__SHAPE = MAP_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Pipe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE_FEATURE_COUNT = MAP_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.pa19.PipeQueue <em>Pipe Queue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.PipeQueue
   * @see edu.pa19.Pa19Package#getPipeQueue()
   * @generated
   */
  public static final int PIPE_QUEUE = 6;

  /**
   * The feature id for the '<em><b>Max Gen Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE_QUEUE__MAX_GEN_LENGTH = 0;

  /**
   * The feature id for the '<em><b>Pipe Queue</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE_QUEUE__PIPE_QUEUE = 1;

  /**
   * The number of structural features of the '<em>Pipe Queue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PIPE_QUEUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.pa19.DelayBar <em>Delay Bar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.DelayBar
   * @see edu.pa19.Pa19Package#getDelayBar()
   * @generated
   */
  public static final int DELAY_BAR = 7;

  /**
   * The feature id for the '<em><b>Initial Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DELAY_BAR__INITIAL_VALUE = 0;

  /**
   * The feature id for the '<em><b>Current Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DELAY_BAR__CURRENT_VALUE = 1;

  /**
   * The number of structural features of the '<em>Delay Bar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DELAY_BAR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.pa19.CellStack <em>Cell Stack</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.CellStack
   * @see edu.pa19.Pa19Package#getCellStack()
   * @generated
   */
  public static final int CELL_STACK = 8;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CELL_STACK__COUNT = 0;

  /**
   * The feature id for the '<em><b>Stack</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CELL_STACK__STACK = 1;

  /**
   * The number of structural features of the '<em>Cell Stack</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CELL_STACK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.pa19.Coordinate <em>Coordinate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Coordinate
   * @see edu.pa19.Pa19Package#getCoordinate()
   * @generated
   */
  public static final int COORDINATE = 9;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COORDINATE__ROW = 0;

  /**
   * The feature id for the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COORDINATE__COL = 1;

  /**
   * The number of structural features of the '<em>Coordinate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COORDINATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.pa19.Map <em>Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Map
   * @see edu.pa19.Pa19Package#getMap()
   * @generated
   */
  public static final int MAP = 10;

  /**
   * The feature id for the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__ROWS = 0;

  /**
   * The feature id for the '<em><b>Cols</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__COLS = 1;

  /**
   * The feature id for the '<em><b>Prev Filled Tiles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__PREV_FILLED_TILES = 2;

  /**
   * The feature id for the '<em><b>Prev Filled Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__PREV_FILLED_DISTANCE = 3;

  /**
   * The feature id for the '<em><b>Source Cell</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__SOURCE_CELL = 4;

  /**
   * The feature id for the '<em><b>Sink Cell</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__SINK_CELL = 5;

  /**
   * The feature id for the '<em><b>Filled Tiles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__FILLED_TILES = 6;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__CELLS = 7;

  /**
   * The feature id for the '<em><b>Cell</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP__CELL = 8;

  /**
   * The number of structural features of the '<em>Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MAP_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link edu.pa19.TerminationCreateInfo <em>Termination Create Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.TerminationCreateInfo
   * @see edu.pa19.Pa19Package#getTerminationCreateInfo()
   * @generated
   */
  public static final int TERMINATION_CREATE_INFO = 12;

  /**
   * The feature id for the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CREATE_INFO__COORD = 0;

  /**
   * The feature id for the '<em><b>Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CREATE_INFO__DIR = 1;

  /**
   * The number of structural features of the '<em>Termination Create Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TERMINATION_CREATE_INFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.pa19.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Direction
   * @see edu.pa19.Pa19Package#getDirection()
   * @generated
   */
  public static final int DIRECTION = 13;

  /**
   * The meta object id for the '{@link edu.pa19.PipeShape <em>Pipe Shape</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.PipeShape
   * @see edu.pa19.Pa19Package#getPipeShape()
   * @generated
   */
  public static final int PIPE_SHAPE = 14;

  /**
   * The meta object id for the '{@link edu.pa19.TerminationType <em>Termination Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.TerminationType
   * @see edu.pa19.Pa19Package#getTerminationType()
   * @generated
   */
  public static final int TERMINATION_TYPE = 15;

  /**
   * The meta object id for the '<em>cellarray</em>' data type.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.pa19.Pa19Package#getcellarray()
   * @generated
   */
  public static final int CELLARRAY = 16;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass gameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cellEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fillableCellEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass wallEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminationCellEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pipeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pipeQueueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass delayBarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cellStackEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass coordinateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mapEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mapElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminationCreateInfoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum directionEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum pipeShapeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum terminationTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EDataType cellarrayEDataType = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.pa19.Pa19Package#eNS_URI
   * @see #init()
   * @generated
   */
  private Pa19Package()
  {
    super(eNS_URI, Pa19Factory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link Pa19Package#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static Pa19Package init()
  {
    if (isInited) return (Pa19Package)EPackage.Registry.INSTANCE.getEPackage(Pa19Package.eNS_URI);

    // Obtain or create and register package
    Object registeredPa19Package = EPackage.Registry.INSTANCE.get(eNS_URI);
    Pa19Package thePa19Package = registeredPa19Package instanceof Pa19Package ? (Pa19Package)registeredPa19Package : new Pa19Package();

    isInited = true;

    // Create package meta-data objects
    thePa19Package.createPackageContents();

    // Initialize created meta-data
    thePa19Package.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePa19Package.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(Pa19Package.eNS_URI, thePa19Package);
    return thePa19Package;
  }


  /**
   * Returns the meta object for class '{@link edu.pa19.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see edu.pa19.Game
   * @generated
   */
  public EClass getGame()
  {
    return gameEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Game#getNumOfSteps <em>Num Of Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Of Steps</em>'.
   * @see edu.pa19.Game#getNumOfSteps()
   * @see #getGame()
   * @generated
   */
  public EAttribute getGame_NumOfSteps()
  {
    return (EAttribute)gameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.Game#getMap <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Map</em>'.
   * @see edu.pa19.Game#getMap()
   * @see #getGame()
   * @generated
   */
  public EReference getGame_Map()
  {
    return (EReference)gameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.Game#getPipeQueue <em>Pipe Queue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pipe Queue</em>'.
   * @see edu.pa19.Game#getPipeQueue()
   * @see #getGame()
   * @generated
   */
  public EReference getGame_PipeQueue()
  {
    return (EReference)gameEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.Game#getDelayBar <em>Delay Bar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay Bar</em>'.
   * @see edu.pa19.Game#getDelayBar()
   * @see #getGame()
   * @generated
   */
  public EReference getGame_DelayBar()
  {
    return (EReference)gameEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.Game#getCellStack <em>Cell Stack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cell Stack</em>'.
   * @see edu.pa19.Game#getCellStack()
   * @see #getGame()
   * @generated
   */
  public EReference getGame_CellStack()
  {
    return (EReference)gameEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see edu.pa19.Cell
   * @generated
   */
  public EClass getCell()
  {
    return cellEClass;
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.Cell#getCoord <em>Coord</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coord</em>'.
   * @see edu.pa19.Cell#getCoord()
   * @see #getCell()
   * @generated
   */
  public EReference getCell_Coord()
  {
    return (EReference)cellEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.FillableCell <em>Fillable Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fillable Cell</em>'.
   * @see edu.pa19.FillableCell
   * @generated
   */
  public EClass getFillableCell()
  {
    return fillableCellEClass;
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.FillableCell#getPipe <em>Pipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pipe</em>'.
   * @see edu.pa19.FillableCell#getPipe()
   * @see #getFillableCell()
   * @generated
   */
  public EReference getFillableCell_Pipe()
  {
    return (EReference)fillableCellEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.Wall <em>Wall</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wall</em>'.
   * @see edu.pa19.Wall
   * @generated
   */
  public EClass getWall()
  {
    return wallEClass;
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.TerminationCell <em>Termination Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termination Cell</em>'.
   * @see edu.pa19.TerminationCell
   * @generated
   */
  public EClass getTerminationCell()
  {
    return terminationCellEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.TerminationCell#isIsFilled <em>Is Filled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Filled</em>'.
   * @see edu.pa19.TerminationCell#isIsFilled()
   * @see #getTerminationCell()
   * @generated
   */
  public EAttribute getTerminationCell_IsFilled()
  {
    return (EAttribute)terminationCellEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.TerminationCell#getPointingTo <em>Pointing To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pointing To</em>'.
   * @see edu.pa19.TerminationCell#getPointingTo()
   * @see #getTerminationCell()
   * @generated
   */
  public EAttribute getTerminationCell_PointingTo()
  {
    return (EAttribute)terminationCellEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.TerminationCell#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.pa19.TerminationCell#getType()
   * @see #getTerminationCell()
   * @generated
   */
  public EAttribute getTerminationCell_Type()
  {
    return (EAttribute)terminationCellEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.Pipe <em>Pipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pipe</em>'.
   * @see edu.pa19.Pipe
   * @generated
   */
  public EClass getPipe()
  {
    return pipeEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Pipe#isFilled <em>Filled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filled</em>'.
   * @see edu.pa19.Pipe#isFilled()
   * @see #getPipe()
   * @generated
   */
  public EAttribute getPipe_Filled()
  {
    return (EAttribute)pipeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Pipe#getShape <em>Shape</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Shape</em>'.
   * @see edu.pa19.Pipe#getShape()
   * @see #getPipe()
   * @generated
   */
  public EAttribute getPipe_Shape()
  {
    return (EAttribute)pipeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.PipeQueue <em>Pipe Queue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pipe Queue</em>'.
   * @see edu.pa19.PipeQueue
   * @generated
   */
  public EClass getPipeQueue()
  {
    return pipeQueueEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.PipeQueue#getMaxGenLength <em>Max Gen Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Gen Length</em>'.
   * @see edu.pa19.PipeQueue#getMaxGenLength()
   * @see #getPipeQueue()
   * @generated
   */
  public EAttribute getPipeQueue_MaxGenLength()
  {
    return (EAttribute)pipeQueueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.pa19.PipeQueue#getPipeQueue <em>Pipe Queue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pipe Queue</em>'.
   * @see edu.pa19.PipeQueue#getPipeQueue()
   * @see #getPipeQueue()
   * @generated
   */
  public EReference getPipeQueue_PipeQueue()
  {
    return (EReference)pipeQueueEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.DelayBar <em>Delay Bar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delay Bar</em>'.
   * @see edu.pa19.DelayBar
   * @generated
   */
  public EClass getDelayBar()
  {
    return delayBarEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.DelayBar#getInitialValue <em>Initial Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Initial Value</em>'.
   * @see edu.pa19.DelayBar#getInitialValue()
   * @see #getDelayBar()
   * @generated
   */
  public EAttribute getDelayBar_InitialValue()
  {
    return (EAttribute)delayBarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.DelayBar#getCurrentValue <em>Current Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Current Value</em>'.
   * @see edu.pa19.DelayBar#getCurrentValue()
   * @see #getDelayBar()
   * @generated
   */
  public EAttribute getDelayBar_CurrentValue()
  {
    return (EAttribute)delayBarEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.CellStack <em>Cell Stack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Stack</em>'.
   * @see edu.pa19.CellStack
   * @generated
   */
  public EClass getCellStack()
  {
    return cellStackEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.CellStack#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see edu.pa19.CellStack#getCount()
   * @see #getCellStack()
   * @generated
   */
  public EAttribute getCellStack_Count()
  {
    return (EAttribute)cellStackEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.pa19.CellStack#getStack <em>Stack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stack</em>'.
   * @see edu.pa19.CellStack#getStack()
   * @see #getCellStack()
   * @generated
   */
  public EReference getCellStack_Stack()
  {
    return (EReference)cellStackEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.Coordinate <em>Coordinate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinate</em>'.
   * @see edu.pa19.Coordinate
   * @generated
   */
  public EClass getCoordinate()
  {
    return coordinateEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Coordinate#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see edu.pa19.Coordinate#getRow()
   * @see #getCoordinate()
   * @generated
   */
  public EAttribute getCoordinate_Row()
  {
    return (EAttribute)coordinateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Coordinate#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col</em>'.
   * @see edu.pa19.Coordinate#getCol()
   * @see #getCoordinate()
   * @generated
   */
  public EAttribute getCoordinate_Col()
  {
    return (EAttribute)coordinateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.Map <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map</em>'.
   * @see edu.pa19.Map
   * @generated
   */
  public EClass getMap()
  {
    return mapEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Map#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rows</em>'.
   * @see edu.pa19.Map#getRows()
   * @see #getMap()
   * @generated
   */
  public EAttribute getMap_Rows()
  {
    return (EAttribute)mapEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Map#getCols <em>Cols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cols</em>'.
   * @see edu.pa19.Map#getCols()
   * @see #getMap()
   * @generated
   */
  public EAttribute getMap_Cols()
  {
    return (EAttribute)mapEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Map#getPrevFilledTiles <em>Prev Filled Tiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prev Filled Tiles</em>'.
   * @see edu.pa19.Map#getPrevFilledTiles()
   * @see #getMap()
   * @generated
   */
  public EAttribute getMap_PrevFilledTiles()
  {
    return (EAttribute)mapEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Map#getPrevFilledDistance <em>Prev Filled Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prev Filled Distance</em>'.
   * @see edu.pa19.Map#getPrevFilledDistance()
   * @see #getMap()
   * @generated
   */
  public EAttribute getMap_PrevFilledDistance()
  {
    return (EAttribute)mapEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the reference '{@link edu.pa19.Map#getSourceCell <em>Source Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Cell</em>'.
   * @see edu.pa19.Map#getSourceCell()
   * @see #getMap()
   * @generated
   */
  public EReference getMap_SourceCell()
  {
    return (EReference)mapEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for the reference '{@link edu.pa19.Map#getSinkCell <em>Sink Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sink Cell</em>'.
   * @see edu.pa19.Map#getSinkCell()
   * @see #getMap()
   * @generated
   */
  public EReference getMap_SinkCell()
  {
    return (EReference)mapEClass.getEStructuralFeatures().get(5);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.pa19.Map#getFilledTiles <em>Filled Tiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Filled Tiles</em>'.
   * @see edu.pa19.Map#getFilledTiles()
   * @see #getMap()
   * @generated
   */
  public EReference getMap_FilledTiles()
  {
    return (EReference)mapEClass.getEStructuralFeatures().get(6);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.pa19.Map#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see edu.pa19.Map#getCells()
   * @see #getMap()
   * @generated
   */
  public EReference getMap_Cells()
  {
    return (EReference)mapEClass.getEStructuralFeatures().get(7);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.Map#getCell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cell</em>'.
   * @see edu.pa19.Map#getCell()
   * @see #getMap()
   * @generated
   */
  public EAttribute getMap_Cell()
  {
    return (EAttribute)mapEClass.getEStructuralFeatures().get(8);
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.MapElement <em>Map Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Element</em>'.
   * @see edu.pa19.MapElement
   * @generated
   */
  public EClass getMapElement()
  {
    return mapElementEClass;
  }

  /**
   * Returns the meta object for class '{@link edu.pa19.TerminationCreateInfo <em>Termination Create Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termination Create Info</em>'.
   * @see edu.pa19.TerminationCreateInfo
   * @generated
   */
  public EClass getTerminationCreateInfo()
  {
    return terminationCreateInfoEClass;
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.pa19.TerminationCreateInfo#getCoord <em>Coord</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coord</em>'.
   * @see edu.pa19.TerminationCreateInfo#getCoord()
   * @see #getTerminationCreateInfo()
   * @generated
   */
  public EReference getTerminationCreateInfo_Coord()
  {
    return (EReference)terminationCreateInfoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.pa19.TerminationCreateInfo#getDir <em>Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dir</em>'.
   * @see edu.pa19.TerminationCreateInfo#getDir()
   * @see #getTerminationCreateInfo()
   * @generated
   */
  public EAttribute getTerminationCreateInfo_Dir()
  {
    return (EAttribute)terminationCreateInfoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for enum '{@link edu.pa19.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see edu.pa19.Direction
   * @generated
   */
  public EEnum getDirection()
  {
    return directionEEnum;
  }

  /**
   * Returns the meta object for enum '{@link edu.pa19.PipeShape <em>Pipe Shape</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Pipe Shape</em>'.
   * @see edu.pa19.PipeShape
   * @generated
   */
  public EEnum getPipeShape()
  {
    return pipeShapeEEnum;
  }

  /**
   * Returns the meta object for enum '{@link edu.pa19.TerminationType <em>Termination Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Termination Type</em>'.
   * @see edu.pa19.TerminationType
   * @generated
   */
  public EEnum getTerminationType()
  {
    return terminationTypeEEnum;
  }

  /**
   * Returns the meta object for data type '<em>cellarray</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for data type '<em>cellarray</em>'.
   * @model instanceClass="edu.pa19.Cell[][]"
   * @generated
   */
  public EDataType getcellarray()
  {
    return cellarrayEDataType;
  }

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  public Pa19Factory getPa19Factory()
  {
    return (Pa19Factory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    gameEClass = createEClass(GAME);
    createEAttribute(gameEClass, GAME__NUM_OF_STEPS);
    createEReference(gameEClass, GAME__MAP);
    createEReference(gameEClass, GAME__PIPE_QUEUE);
    createEReference(gameEClass, GAME__DELAY_BAR);
    createEReference(gameEClass, GAME__CELL_STACK);

    cellEClass = createEClass(CELL);
    createEReference(cellEClass, CELL__COORD);

    fillableCellEClass = createEClass(FILLABLE_CELL);
    createEReference(fillableCellEClass, FILLABLE_CELL__PIPE);

    wallEClass = createEClass(WALL);

    terminationCellEClass = createEClass(TERMINATION_CELL);
    createEAttribute(terminationCellEClass, TERMINATION_CELL__IS_FILLED);
    createEAttribute(terminationCellEClass, TERMINATION_CELL__POINTING_TO);
    createEAttribute(terminationCellEClass, TERMINATION_CELL__TYPE);

    pipeEClass = createEClass(PIPE);
    createEAttribute(pipeEClass, PIPE__FILLED);
    createEAttribute(pipeEClass, PIPE__SHAPE);

    pipeQueueEClass = createEClass(PIPE_QUEUE);
    createEAttribute(pipeQueueEClass, PIPE_QUEUE__MAX_GEN_LENGTH);
    createEReference(pipeQueueEClass, PIPE_QUEUE__PIPE_QUEUE);

    delayBarEClass = createEClass(DELAY_BAR);
    createEAttribute(delayBarEClass, DELAY_BAR__INITIAL_VALUE);
    createEAttribute(delayBarEClass, DELAY_BAR__CURRENT_VALUE);

    cellStackEClass = createEClass(CELL_STACK);
    createEAttribute(cellStackEClass, CELL_STACK__COUNT);
    createEReference(cellStackEClass, CELL_STACK__STACK);

    coordinateEClass = createEClass(COORDINATE);
    createEAttribute(coordinateEClass, COORDINATE__ROW);
    createEAttribute(coordinateEClass, COORDINATE__COL);

    mapEClass = createEClass(MAP);
    createEAttribute(mapEClass, MAP__ROWS);
    createEAttribute(mapEClass, MAP__COLS);
    createEAttribute(mapEClass, MAP__PREV_FILLED_TILES);
    createEAttribute(mapEClass, MAP__PREV_FILLED_DISTANCE);
    createEReference(mapEClass, MAP__SOURCE_CELL);
    createEReference(mapEClass, MAP__SINK_CELL);
    createEReference(mapEClass, MAP__FILLED_TILES);
    createEReference(mapEClass, MAP__CELLS);
    createEAttribute(mapEClass, MAP__CELL);

    mapElementEClass = createEClass(MAP_ELEMENT);

    terminationCreateInfoEClass = createEClass(TERMINATION_CREATE_INFO);
    createEReference(terminationCreateInfoEClass, TERMINATION_CREATE_INFO__COORD);
    createEAttribute(terminationCreateInfoEClass, TERMINATION_CREATE_INFO__DIR);

    // Create enums
    directionEEnum = createEEnum(DIRECTION);
    pipeShapeEEnum = createEEnum(PIPE_SHAPE);
    terminationTypeEEnum = createEEnum(TERMINATION_TYPE);

    // Create data types
    cellarrayEDataType = createEDataType(CELLARRAY);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    cellEClass.getESuperTypes().add(this.getMapElement());
    fillableCellEClass.getESuperTypes().add(this.getCell());
    wallEClass.getESuperTypes().add(this.getCell());
    terminationCellEClass.getESuperTypes().add(this.getCell());
    pipeEClass.getESuperTypes().add(this.getMapElement());

    // Initialize classes and features; add operations and parameters
    initEClass(gameEClass, Game.class, "Game", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGame_NumOfSteps(), ecorePackage.getEInt(), "numOfSteps", "0", 0, 1, Game.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGame_Map(), this.getMap(), null, "map", null, 0, 1, Game.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGame_PipeQueue(), this.getPipeQueue(), null, "pipeQueue", null, 0, 1, Game.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGame_DelayBar(), this.getDelayBar(), null, "delayBar", null, 0, 1, Game.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGame_CellStack(), this.getCellStack(), null, "cellStack", null, 0, 1, Game.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    EOperation op = addEOperation(gameEClass, ecorePackage.getEBoolean(), "placePipe", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "row", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEChar(), "col", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(gameEClass, null, "skipPipe", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(gameEClass, ecorePackage.getEBoolean(), "undoStep", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(gameEClass, null, "updateState", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(gameEClass, ecorePackage.getEBoolean(), "hasWon", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(gameEClass, ecorePackage.getEBoolean(), "hasLost", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(gameEClass, this.getGame(), "fromString", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "rows", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "cols", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "delay", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "cellsrep", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getPipe(), "pipes", 0, -1, IS_UNIQUE, IS_ORDERED);

    initEClass(cellEClass, Cell.class, "Cell", IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCell_Coord(), this.getCoordinate(), null, "coord", null, 0, 1, Cell.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(cellEClass, this.getCell(), "fromChar", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEChar(), "c", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCoordinate(), "coord", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTerminationType(), "terminationType", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(fillableCellEClass, FillableCell.class, "FillableCell", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFillableCell_Pipe(), this.getPipe(), null, "pipe", null, 0, 1, FillableCell.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(fillableCellEClass, ecorePackage.getEChar(), "toSingleChar", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(wallEClass, Wall.class, "Wall", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    addEOperation(wallEClass, ecorePackage.getEChar(), "toSingleChar", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(terminationCellEClass, TerminationCell.class, "TerminationCell", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTerminationCell_IsFilled(), ecorePackage.getEBoolean(), "isFilled", "false", 0, 1, TerminationCell.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTerminationCell_PointingTo(), this.getDirection(), "pointingTo", null, 1, 1, TerminationCell.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTerminationCell_Type(), this.getTerminationType(), "type", null, 0, 1, TerminationCell.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(terminationCellEClass, null, "toSingleChar", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(pipeEClass, Pipe.class, "Pipe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPipe_Filled(), ecorePackage.getEBoolean(), "filled", "false", 0, 1, Pipe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPipe_Shape(), this.getPipeShape(), "shape", null, 1, 1, Pipe.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(pipeEClass, this.getDirection(), "getConnections", 0, -1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(pipeEClass, this.getPipe(), "fromString", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "rep", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(pipeEClass, ecorePackage.getEChar(), "toSingleChar", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(pipeQueueEClass, PipeQueue.class, "PipeQueue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPipeQueue_MaxGenLength(), ecorePackage.getEInt(), "maxGenLength", "5", 0, 1, PipeQueue.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPipeQueue_PipeQueue(), this.getPipe(), null, "pipeQueue", null, 0, -1, PipeQueue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(pipeQueueEClass, this.getPipe(), "peek", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(pipeQueueEClass, null, "consume", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(pipeQueueEClass, null, "undo", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getPipe(), "pipe", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(pipeQueueEClass, null, "display", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(pipeQueueEClass, this.getPipe(), "generateNewPipe", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(delayBarEClass, DelayBar.class, "DelayBar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDelayBar_InitialValue(), ecorePackage.getEInt(), "initialValue", null, 0, 1, DelayBar.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDelayBar_CurrentValue(), ecorePackage.getEInt(), "currentValue", null, 0, 1, DelayBar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(delayBarEClass, null, "countdown", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(delayBarEClass, ecorePackage.getEInt(), "distance", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(delayBarEClass, null, "display", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(cellStackEClass, CellStack.class, "CellStack", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCellStack_Count(), ecorePackage.getEInt(), "count", null, 0, 1, CellStack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCellStack_Stack(), this.getFillableCell(), null, "stack", null, 0, -1, CellStack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(cellStackEClass, null, "push", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getFillableCell(), "cell", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(cellStackEClass, this.getFillableCell(), "pop", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(cellStackEClass, ecorePackage.getEInt(), "getUndoCount", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(cellStackEClass, null, "display", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(coordinateEClass, Coordinate.class, "Coordinate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCoordinate_Row(), ecorePackage.getEInt(), "row", null, 0, 1, Coordinate.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCoordinate_Col(), ecorePackage.getEInt(), "col", null, 0, 1, Coordinate.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(coordinateEClass, this.getCoordinate(), "add", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCoordinate(), "other", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(mapEClass, Map.class, "Map", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMap_Rows(), ecorePackage.getEInt(), "rows", null, 1, 1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMap_Cols(), ecorePackage.getEInt(), "cols", null, 1, 1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMap_PrevFilledTiles(), ecorePackage.getEInt(), "prevFilledTiles", null, 0, 1, Map.class, IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMap_PrevFilledDistance(), ecorePackage.getEIntegerObject(), "prevFilledDistance", null, 0, 1, Map.class, IS_TRANSIENT, !IS_VOLATILE, !IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMap_SourceCell(), this.getTerminationCell(), null, "sourceCell", null, 1, 1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMap_SinkCell(), this.getTerminationCell(), null, "sinkCell", null, 1, 1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMap_FilledTiles(), this.getCoordinate(), null, "filledTiles", null, 0, -1, Map.class, IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMap_Cells(), this.getCell(), null, "cells", null, 0, -1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMap_Cell(), this.getcellarray(), "cell", null, 0, 1, Map.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(mapEClass, ecorePackage.getEBoolean(), "tryPlacePipe", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCoordinate(), "coord", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getPipe(), "pipe", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(mapEClass, null, "undo", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCoordinate(), "coord", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(mapEClass, null, "fillBeginTile", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(mapEClass, null, "fillTiles", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "distance", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(mapEClass, ecorePackage.getEBoolean(), "checkPath", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(mapEClass, ecorePackage.getEBoolean(), "hasLost", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(mapEClass, null, "display", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(mapEClass, this.getMap(), "fromString", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "r", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "c", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "rep", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(mapElementEClass, MapElement.class, "MapElement", IS_ABSTRACT, IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    addEOperation(mapElementEClass, ecorePackage.getEChar(), "toSingleChar", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(terminationCreateInfoEClass, TerminationCreateInfo.class, "TerminationCreateInfo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTerminationCreateInfo_Coord(), this.getCoordinate(), null, "coord", null, 0, 1, TerminationCreateInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTerminationCreateInfo_Dir(), this.getDirection(), "dir", null, 0, 1, TerminationCreateInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(directionEEnum, Direction.class, "Direction");
    addEEnumLiteral(directionEEnum, Direction.UP);
    addEEnumLiteral(directionEEnum, Direction.DOWN);
    addEEnumLiteral(directionEEnum, Direction.LEFT);
    addEEnumLiteral(directionEEnum, Direction.RIGHT);

    initEEnum(pipeShapeEEnum, PipeShape.class, "PipeShape");
    addEEnumLiteral(pipeShapeEEnum, PipeShape.HORIZONTAL);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.VERTICAL);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.TOP_LEFT);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.TOP_RIGHT);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.BOTTOM_LEFT);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.BOTTOM_RIGHT);
    addEEnumLiteral(pipeShapeEEnum, PipeShape.CROSS);

    initEEnum(terminationTypeEEnum, TerminationType.class, "TerminationType");
    addEEnumLiteral(terminationTypeEEnum, TerminationType.SOURCE);
    addEEnumLiteral(terminationTypeEEnum, TerminationType.SINK);

    // Initialize data types
    initEDataType(cellarrayEDataType, Cell[][].class, "cellarray", IS_SERIALIZABLE, !IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);

    // Create annotations
    // http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen
    createEnhancedCodeGenAnnotations();
  }

  /**
   * Initializes the annotations for <b>http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen</b>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void createEnhancedCodeGenAnnotations()
  {
    String source = "http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen";
    addAnnotation
      (this,
       source,
       new String[]
       {
         "requirement", "Overall/Domain\n\nConsole pipe-connection game: grid with outer walls, one source inside pointing inward, one sink on the border pointing outward. Player places pipes from a queue; after a delay, water flows along placed pipes.\nCoordinates are 1-based. Direction provides four directions plus opposite/offset; PipeShape defines connection directions; TerminationType distinguishes SOURCE vs SINK.\nFunctional requirements (for generated EOperations; coarse-grained)\n\nGame: operations to place a pipe, skip, undo, advance water flow, check win, check loss; convenience fromString constructor; maintain step count.\nMap: operations to place pipe (by coord or row/col), undo a cell, start filling from source, expand filling by distance, check path existence, check loss state; access cells in flattened list with row/col attributes.\nCell family: Cell.fromChar parses map chars to concrete cells; FillableCell holds an optional pipe and renders pipe or \'.\'; TerminationCell renders arrows by filled state and direction; Wall renders wall char.\nPipe: expose connection directions, char rendering by filled/unfilled, construct from short string code.\nPipeQueue: peek/consume/undo head pipe and auto-refill to fixed length with random shapes.\nDelayBar: countdown and report flow distance; optional display.\nCellStack: push/pop last placement, report undo count; optional display.\nExternal/tool classes (not generated; handwritten or reused)\n\nDeserializer: read rows/cols/delay, map chars, and optional default pipes from file/string; build Cell[][] and construct Game.\nPipePatterns: constants for wall, arrows, and each pipe shape in filled/unfilled states.\nStringUtils: simple repeat/padding utility for UI.\nMain (CLI): parse args (file or size), loop render/read input and drive Game; outside the model."
       });
    addAnnotation
      (gameEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(4),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(5),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (gameEClass.getEOperations().get(6),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (cellEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (fillableCellEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (wallEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (terminationCellEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeQueueEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeQueueEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeQueueEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeQueueEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (pipeQueueEClass.getEOperations().get(4),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (delayBarEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (delayBarEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (delayBarEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (cellStackEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (cellStackEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (cellStackEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (cellStackEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (coordinateEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(4),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(5),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(6),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (mapEClass.getEOperations().get(7),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (getMap_Cells(),
       source,
       new String[]
       {
         "requirement", "{\n  \"feature\": \"cells\",\n  \"pattern\": \"Flattened2DArray\",\n  \"logic\": {\n    \"indexing\": \"Row-Major Order\",\n    \"formula\": \"index = row * cols + col\",\n    \"access_methods\": [\n      {\n        \"name\": \"getCell\",\n        \"params\": [\"int row\", \"int col\"],\n        \"body\": \"return getCells().get(row * getCols() + col);\"\n      },\n      {\n        \"name\": \"setCell\",\n        \"params\": [\"int row\", \"int col\", \"Cell cell\"],\n        \"body\": \"getCells().set(row * getCols() + col, cell);\"\n      }\n    ]\n  },\n  \"constraints\": [\n    \"Total size must be rows * cols\",\n    \"Boundary check: 0 <= row < rows && 0 <= col < cols\"\n  ]\n}"
       });
    addAnnotation
      (pipeShapeEEnum,
       source,
       new String[]
       {
         "requirement", "{\n  \"PipeShapeMapping\": {\n    \"HORIZONTAL\": {\n      \"mapping_key\": \"mapping_HZ\",\n      \"filled\": \"PipePatterns.Filled.HORIZONTAL\",\n      \"unfilled\": \"PipePatterns.Unfilled.HORIZONTAL\"\n    },\n    \"VERTICAL\": {\n      \"mapping_key\": \"mapping_VT\",\n      \"filled\": \"PipePatterns.Filled.VERTICAL\",\n      \"unfilled\": \"PipePatterns.Unfilled.VERTICAL\"\n    },\n    \"TOP_LEFT\": {\n      \"mapping_key\": \"mapping_TL\",\n      \"filled\": \"PipePatterns.Filled.TOP_LEFT\",\n      \"unfilled\": \"PipePatterns.Unfilled.TOP_LEFT\"\n    },\n    \"CROSS\": {\n      \"mapping_key\": \"mapping_CROSS\",\n      \"filled\": \"PipePatterns.Filled.CROSS\",\n      \"unfilled\": \"PipePatterns.Unfilled.CROSS\"\n    }\n  }\n}"
       });
    addAnnotation
      (mapElementEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
  }

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  public interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.pa19.Game <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Game
     * @see edu.pa19.Pa19Package#getGame()
     * @generated
     */
    public static final EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Num Of Steps</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute GAME__NUM_OF_STEPS = eINSTANCE.getGame_NumOfSteps();

    /**
     * The meta object literal for the '<em><b>Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference GAME__MAP = eINSTANCE.getGame_Map();

    /**
     * The meta object literal for the '<em><b>Pipe Queue</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference GAME__PIPE_QUEUE = eINSTANCE.getGame_PipeQueue();

    /**
     * The meta object literal for the '<em><b>Delay Bar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference GAME__DELAY_BAR = eINSTANCE.getGame_DelayBar();

    /**
     * The meta object literal for the '<em><b>Cell Stack</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference GAME__CELL_STACK = eINSTANCE.getGame_CellStack();

    /**
     * The meta object literal for the '{@link edu.pa19.Cell <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Cell
     * @see edu.pa19.Pa19Package#getCell()
     * @generated
     */
    public static final EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Coord</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference CELL__COORD = eINSTANCE.getCell_Coord();

    /**
     * The meta object literal for the '{@link edu.pa19.FillableCell <em>Fillable Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.FillableCell
     * @see edu.pa19.Pa19Package#getFillableCell()
     * @generated
     */
    public static final EClass FILLABLE_CELL = eINSTANCE.getFillableCell();

    /**
     * The meta object literal for the '<em><b>Pipe</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference FILLABLE_CELL__PIPE = eINSTANCE.getFillableCell_Pipe();

    /**
     * The meta object literal for the '{@link edu.pa19.Wall <em>Wall</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Wall
     * @see edu.pa19.Pa19Package#getWall()
     * @generated
     */
    public static final EClass WALL = eINSTANCE.getWall();

    /**
     * The meta object literal for the '{@link edu.pa19.TerminationCell <em>Termination Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.TerminationCell
     * @see edu.pa19.Pa19Package#getTerminationCell()
     * @generated
     */
    public static final EClass TERMINATION_CELL = eINSTANCE.getTerminationCell();

    /**
     * The meta object literal for the '<em><b>Is Filled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TERMINATION_CELL__IS_FILLED = eINSTANCE.getTerminationCell_IsFilled();

    /**
     * The meta object literal for the '<em><b>Pointing To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TERMINATION_CELL__POINTING_TO = eINSTANCE.getTerminationCell_PointingTo();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TERMINATION_CELL__TYPE = eINSTANCE.getTerminationCell_Type();

    /**
     * The meta object literal for the '{@link edu.pa19.Pipe <em>Pipe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Pipe
     * @see edu.pa19.Pa19Package#getPipe()
     * @generated
     */
    public static final EClass PIPE = eINSTANCE.getPipe();

    /**
     * The meta object literal for the '<em><b>Filled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PIPE__FILLED = eINSTANCE.getPipe_Filled();

    /**
     * The meta object literal for the '<em><b>Shape</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PIPE__SHAPE = eINSTANCE.getPipe_Shape();

    /**
     * The meta object literal for the '{@link edu.pa19.PipeQueue <em>Pipe Queue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.PipeQueue
     * @see edu.pa19.Pa19Package#getPipeQueue()
     * @generated
     */
    public static final EClass PIPE_QUEUE = eINSTANCE.getPipeQueue();

    /**
     * The meta object literal for the '<em><b>Max Gen Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PIPE_QUEUE__MAX_GEN_LENGTH = eINSTANCE.getPipeQueue_MaxGenLength();

    /**
     * The meta object literal for the '<em><b>Pipe Queue</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference PIPE_QUEUE__PIPE_QUEUE = eINSTANCE.getPipeQueue_PipeQueue();

    /**
     * The meta object literal for the '{@link edu.pa19.DelayBar <em>Delay Bar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.DelayBar
     * @see edu.pa19.Pa19Package#getDelayBar()
     * @generated
     */
    public static final EClass DELAY_BAR = eINSTANCE.getDelayBar();

    /**
     * The meta object literal for the '<em><b>Initial Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute DELAY_BAR__INITIAL_VALUE = eINSTANCE.getDelayBar_InitialValue();

    /**
     * The meta object literal for the '<em><b>Current Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute DELAY_BAR__CURRENT_VALUE = eINSTANCE.getDelayBar_CurrentValue();

    /**
     * The meta object literal for the '{@link edu.pa19.CellStack <em>Cell Stack</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.CellStack
     * @see edu.pa19.Pa19Package#getCellStack()
     * @generated
     */
    public static final EClass CELL_STACK = eINSTANCE.getCellStack();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute CELL_STACK__COUNT = eINSTANCE.getCellStack_Count();

    /**
     * The meta object literal for the '<em><b>Stack</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference CELL_STACK__STACK = eINSTANCE.getCellStack_Stack();

    /**
     * The meta object literal for the '{@link edu.pa19.Coordinate <em>Coordinate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Coordinate
     * @see edu.pa19.Pa19Package#getCoordinate()
     * @generated
     */
    public static final EClass COORDINATE = eINSTANCE.getCoordinate();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute COORDINATE__ROW = eINSTANCE.getCoordinate_Row();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute COORDINATE__COL = eINSTANCE.getCoordinate_Col();

    /**
     * The meta object literal for the '{@link edu.pa19.Map <em>Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Map
     * @see edu.pa19.Pa19Package#getMap()
     * @generated
     */
    public static final EClass MAP = eINSTANCE.getMap();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MAP__ROWS = eINSTANCE.getMap_Rows();

    /**
     * The meta object literal for the '<em><b>Cols</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MAP__COLS = eINSTANCE.getMap_Cols();

    /**
     * The meta object literal for the '<em><b>Prev Filled Tiles</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MAP__PREV_FILLED_TILES = eINSTANCE.getMap_PrevFilledTiles();

    /**
     * The meta object literal for the '<em><b>Prev Filled Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MAP__PREV_FILLED_DISTANCE = eINSTANCE.getMap_PrevFilledDistance();

    /**
     * The meta object literal for the '<em><b>Source Cell</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference MAP__SOURCE_CELL = eINSTANCE.getMap_SourceCell();

    /**
     * The meta object literal for the '<em><b>Sink Cell</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference MAP__SINK_CELL = eINSTANCE.getMap_SinkCell();

    /**
     * The meta object literal for the '<em><b>Filled Tiles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference MAP__FILLED_TILES = eINSTANCE.getMap_FilledTiles();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference MAP__CELLS = eINSTANCE.getMap_Cells();

    /**
     * The meta object literal for the '<em><b>Cell</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MAP__CELL = eINSTANCE.getMap_Cell();

    /**
     * The meta object literal for the '{@link edu.pa19.MapElement <em>Map Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.MapElement
     * @see edu.pa19.Pa19Package#getMapElement()
     * @generated
     */
    public static final EClass MAP_ELEMENT = eINSTANCE.getMapElement();

    /**
     * The meta object literal for the '{@link edu.pa19.TerminationCreateInfo <em>Termination Create Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.TerminationCreateInfo
     * @see edu.pa19.Pa19Package#getTerminationCreateInfo()
     * @generated
     */
    public static final EClass TERMINATION_CREATE_INFO = eINSTANCE.getTerminationCreateInfo();

    /**
     * The meta object literal for the '<em><b>Coord</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference TERMINATION_CREATE_INFO__COORD = eINSTANCE.getTerminationCreateInfo_Coord();

    /**
     * The meta object literal for the '<em><b>Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TERMINATION_CREATE_INFO__DIR = eINSTANCE.getTerminationCreateInfo_Dir();

    /**
     * The meta object literal for the '{@link edu.pa19.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Direction
     * @see edu.pa19.Pa19Package#getDirection()
     * @generated
     */
    public static final EEnum DIRECTION = eINSTANCE.getDirection();

    /**
     * The meta object literal for the '{@link edu.pa19.PipeShape <em>Pipe Shape</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.PipeShape
     * @see edu.pa19.Pa19Package#getPipeShape()
     * @generated
     */
    public static final EEnum PIPE_SHAPE = eINSTANCE.getPipeShape();

    /**
     * The meta object literal for the '{@link edu.pa19.TerminationType <em>Termination Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.TerminationType
     * @see edu.pa19.Pa19Package#getTerminationType()
     * @generated
     */
    public static final EEnum TERMINATION_TYPE = eINSTANCE.getTerminationType();

    /**
     * The meta object literal for the '<em>cellarray</em>' data type.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.pa19.Pa19Package#getcellarray()
     * @generated
     */
    public static final EDataType CELLARRAY = eINSTANCE.getcellarray();

  }

} //Pa19Package
