/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipe</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.Pipe#isFilled <em>Filled</em>}</li>
 *   <li>{@link edu.pa19.Pipe#getShape <em>Shape</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getPipe()
 * @model kind="class"
 * @generated
 */
public class Pipe extends MinimalEObjectImpl.Container implements MapElement
{
  /**
   * The default value of the '{@link #isFilled() <em>Filled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFilled()
   * @generated
   * @ordered
   */
  protected static final boolean FILLED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFilled() <em>Filled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFilled()
   * @generated
   * @ordered
   */
  protected boolean filled = FILLED_EDEFAULT;

  /**
   * The default value of the '{@link #getShape() <em>Shape</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShape()
   * @generated
   * @ordered
   */
  protected static final PipeShape SHAPE_EDEFAULT = PipeShape.HORIZONTAL;

  /**
   * The cached value of the '{@link #getShape() <em>Shape</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShape()
   * @generated
   * @ordered
   */
  protected PipeShape shape = SHAPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Pipe()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.PIPE;
  }

  /**
   * Returns the value of the '<em><b>Filled</b></em>' attribute.
   * The default value is <code>"false"</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filled</em>' attribute.
   * @see #setFilled(boolean)
   * @see edu.pa19.Pa19Package#getPipe_Filled()
   * @model default="false"
   * @generated
   */
  public boolean isFilled()
  {
    return filled;
  }

  /**
   * Sets the value of the '{@link edu.pa19.Pipe#isFilled <em>Filled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newFilled the new value of the '<em>Filled</em>' attribute.
   * @see #isFilled()
   * @generated
   */
  public void setFilled(boolean newFilled)
  {
    boolean oldFilled = filled;
    filled = newFilled;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.PIPE__FILLED, oldFilled, filled));
  }

  /**
   * Returns the value of the '<em><b>Shape</b></em>' attribute.
   * The literals are from the enumeration {@link edu.pa19.PipeShape}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shape</em>' attribute.
   * @see edu.pa19.PipeShape
   * @see edu.pa19.Pa19Package#getPipe_Shape()
   * @model required="true" changeable="false"
   * @generated
   */
  public PipeShape getShape()
  {
    return shape;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns the list of directions that this pipe connects to.
   * Algorithm:
   *   1. Based on the shape, return the predefined list of directions:
   *        - HORIZONTAL: LEFT, RIGHT
   *        - VERTICAL: UP, DOWN
   *        - TOP_LEFT: UP, LEFT
   *        - etc.
   * Related Features: shape.
   * Related Classes: Direction, PipeShape.
   * Input: None.
   * Output: A list of Direction objects (non-null).
   * Pre-condition: None.
   * Post-condition: The pipe state is unchanged.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Direction> getConnections()
  {
    BasicEList<Direction> connections = new BasicEList<>();
    switch (getShape()) {
      case HORIZONTAL:
        connections.add(Direction.get("LEFT"));
        connections.add(Direction.get("RIGHT"));
        break;
      case VERTICAL:
        connections.add(Direction.get("UP"));
        connections.add(Direction.get("DOWN"));
        break;
      case TOP_LEFT:
        connections.add(Direction.get("UP"));
        connections.add(Direction.get("LEFT"));
        break;
      case TOP_RIGHT:
        connections.add(Direction.get("UP"));
        connections.add(Direction.get("RIGHT"));
        break;
      case BOTTOM_LEFT:
        connections.add(Direction.get("DOWN"));
        connections.add(Direction.get("LEFT"));
        break;
      case BOTTOM_RIGHT:
        connections.add(Direction.get("DOWN"));
        connections.add(Direction.get("RIGHT"));
        break;
      default:
        // No connections for unknown shape
        break;
    }
    return connections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Static factory method to create a Pipe from a short string code.
   * Algorithm:
   *   1. Parse the string to determine shape and filled state.
   *   2. For example, "H" might be unfilled horizontal, "H_f" filled horizontal.
   *   3. Return a new Pipe with the given shape and filled state.
   * Related Features: shape, filled.
   * Related Classes: PipeShape.
   * Input:
   *   - rep: A string code representing the pipe (e.g., "H", "V_f").
   * Output: A new Pipe instance.
   * Pre-condition: rep must be a valid pipe code.
   * Post-condition: The pipe's shape and filled state are set accordingly.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Pipe fromString(final String rep)
  {
    Pipe pipe = Pa19Factory.eINSTANCE.createPipe();
    boolean filled = false;
    String shapePart = rep;
    
    if (rep.endsWith("_f")) {
      filled = true;
      shapePart = rep.substring(0, rep.length() - 2);
    }
    
    PipeShape shape;
    switch (shapePart) {
      case "H":
        shape = PipeShape.HORIZONTAL;
        break;
      case "V":
        shape = PipeShape.VERTICAL;
        break;
      case "TL":
        shape = PipeShape.TOP_LEFT;
        break;
      case "TR":
        shape = PipeShape.TOP_RIGHT;
        break;
      case "BL":
        shape = PipeShape.BOTTOM_LEFT;
        break;
      case "BR":
        shape = PipeShape.BOTTOM_RIGHT;
        break;
      default:
        shape = PipeShape.HORIZONTAL; // default fallback
        break;
    }
    
    pipe.setShape(shape);
    pipe.setFilled(filled);
    return pipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns a single character representing this pipe for display.
   * Algorithm:
   *   1. Based on shape and filled state, return the corresponding character from PipePatterns.
   * Related Features: shape, filled.
   * Related Classes: PipeShape.
   * Input: None.
   * Output: A character (e.g., '─' for unfilled horizontal, '═' for filled horizontal).
   * Pre-condition: None.
   * Post-condition: The pipe state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public char toSingleChar()
  {
    boolean filled = isFilled();
    PipeShape shape = getShape();
    
    switch (shape) {
      case HORIZONTAL:
        return filled ? '═' : '─';
      case VERTICAL:
        return filled ? '║' : '│';
      case TOP_LEFT:
        return filled ? '╝' : '┘';
      case TOP_RIGHT:
        return filled ? '╚' : '└';
      case BOTTOM_LEFT:
        return filled ? '╗' : '┐';
      case BOTTOM_RIGHT:
        return filled ? '╔' : '┌';
      default:
        return '?';
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE__FILLED:
        return isFilled();
      case Pa19Package.PIPE__SHAPE:
        return getShape();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE__FILLED:
        setFilled((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE__FILLED:
        setFilled(FILLED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE__FILLED:
        return filled != FILLED_EDEFAULT;
      case Pa19Package.PIPE__SHAPE:
        return shape != SHAPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (filled: ");
    result.append(filled);
    result.append(", shape: ");
    result.append(shape);
    result.append(')');
    return result.toString();
  }

} // Pipe
