/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.Random;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipe Queue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.PipeQueue#getMaxGenLength <em>Max Gen Length</em>}</li>
 *   <li>{@link edu.pa19.PipeQueue#getPipeQueue <em>Pipe Queue</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getPipeQueue()
 * @model kind="class"
 * @generated
 */
public class PipeQueue extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getMaxGenLength() <em>Max Gen Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxGenLength()
   * @generated
   * @ordered
   */
  protected static final int MAX_GEN_LENGTH_EDEFAULT = 5;

  /**
   * The cached value of the '{@link #getMaxGenLength() <em>Max Gen Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxGenLength()
   * @generated
   * @ordered
   */
  protected int maxGenLength = MAX_GEN_LENGTH_EDEFAULT;

  /**
   * The cached value of the '{@link #getPipeQueue() <em>Pipe Queue</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPipeQueue()
   * @generated
   * @ordered
   */
  protected EList<Pipe> pipeQueue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PipeQueue()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.PIPE_QUEUE;
  }

  /**
   * Returns the value of the '<em><b>Max Gen Length</b></em>' attribute.
   * The default value is <code>"5"</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Gen Length</em>' attribute.
   * @see edu.pa19.Pa19Package#getPipeQueue_MaxGenLength()
   * @model default="5" changeable="false"
   * @generated
   */
  public int getMaxGenLength()
  {
    return maxGenLength;
  }

  /**
   * Returns the value of the '<em><b>Pipe Queue</b></em>' containment reference list.
   * The list contents are of type {@link edu.pa19.Pipe}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipe Queue</em>' containment reference list.
   * @see edu.pa19.Pa19Package#getPipeQueue_PipeQueue()
   * @model containment="true"
   * @generated
   */
  public EList<Pipe> getPipeQueue()
  {
    if (pipeQueue == null)
    {
      pipeQueue = new EObjectContainmentEList<Pipe>(Pipe.class, this, Pa19Package.PIPE_QUEUE__PIPE_QUEUE);
    }
    return pipeQueue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns the head pipe without removing it.
   * Algorithm:
   *   1. Return the first element of pipeQueue (or null if empty).
   * Related Features: pipeQueue.
   * Related Classes: Pipe.
   * Input: None.
   * Output: The first Pipe in the queue, or null if empty.
   * Pre-condition: None.
   * Post-condition: The queue state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Pipe peek()
  {
    if (pipeQueue == null || pipeQueue.isEmpty()) {
      return null;
    }
    return pipeQueue.get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes the head pipe from the queue and generates a new one to maintain length.
   * Algorithm:
   *   1. Remove the first pipe from pipeQueue.
   *   2. Call generateNewPipe() and add it to the end of pipeQueue.
   * Related Features: pipeQueue, maxGenLength.
   * Related Classes: Pipe.
   * Input: None.
   * Output: None (void).
   * Pre-condition: pipeQueue is not empty.
   * Post-condition:
   *   - The head pipe is removed.
   *   - A new pipe is added at the end, so queue length remains maxGenLength.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void consume()
  {
    if (pipeQueue == null || pipeQueue.isEmpty()) {
      return;
    }
    pipeQueue.remove(0);
    Pipe newPipe = generateNewPipe();
    pipeQueue.add(newPipe);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Inserts a pipe at the head of the queue (for undo).
   * Algorithm:
   *   1. Insert the given pipe at the beginning of pipeQueue.
   *   2. Remove the last pipe from pipeQueue to maintain maxGenLength.
   * Related Features: pipeQueue, maxGenLength.
   * Related Classes: Pipe.
   * Input:
   *   - pipe: The pipe to insert at the head.
   * Output: None (void).
   * Pre-condition: pipe is not null.
   * Post-condition:
   *   - The pipe is added at the head.
   *   - The queue length remains maxGenLength (last pipe discarded).
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void undo(final Pipe pipe)
  {
    if (pipe == null) {
      return;
    }
    pipeQueue.add(0, pipe);
    if (pipeQueue.size() > maxGenLength) {
      pipeQueue.remove(pipeQueue.size() - 1);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Displays the current pipe queue (for debugging or UI).
   * Algorithm:
   *   1. Print each pipe in pipeQueue (e.g., using pipe.toSingleChar()).
   * Related Features: pipeQueue.
   * Related Classes: Pipe.
   * Input: None.
   * Output: None (void). Output is printed to console or UI.
   * Pre-condition: None.
   * Post-condition: The queue state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void display()
  {
    if (pipeQueue == null) {
      System.out.println("Queue is null");
      return;
    }
    for (Pipe pipe : pipeQueue) {
      System.out.print(pipe.toSingleChar() + " ");
    }
    System.out.println();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Generates a random new pipe (random shape, unfilled).
   * Algorithm:
   *   1. Randomly select a PipeShape from the enum.
   *   2. Return a new Pipe with that shape and filled = false.
   * Related Features: None.
   * Related Classes: Pipe, PipeShape.
   * Input: None.
   * Output: A new Pipe with random shape, unfilled.
   * Pre-condition: None.
   * Post-condition: None.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Pipe generateNewPipe()
  {
    Pipe newPipe = Pa19Factory.eINSTANCE.createPipe();
    PipeShape[] shapes = PipeShape.values();
    Random random = new Random();
    PipeShape randomShape = shapes[random.nextInt(shapes.length)];
    newPipe.setShape(randomShape);
    newPipe.setFilled(false);
    return newPipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE_QUEUE__PIPE_QUEUE:
        return ((InternalEList<?>)getPipeQueue()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE_QUEUE__MAX_GEN_LENGTH:
        return getMaxGenLength();
      case Pa19Package.PIPE_QUEUE__PIPE_QUEUE:
        return getPipeQueue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE_QUEUE__PIPE_QUEUE:
        getPipeQueue().clear();
        getPipeQueue().addAll((Collection<? extends Pipe>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE_QUEUE__PIPE_QUEUE:
        getPipeQueue().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.PIPE_QUEUE__MAX_GEN_LENGTH:
        return maxGenLength != MAX_GEN_LENGTH_EDEFAULT;
      case Pa19Package.PIPE_QUEUE__PIPE_QUEUE:
        return pipeQueue != null && !pipeQueue.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (maxGenLength: ");
    result.append(maxGenLength);
    result.append(')');
    return result.toString();
  }

} // PipeQueue
