/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termination Create Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pa19.TerminationCreateInfo#getCoord <em>Coord</em>}</li>
 *   <li>{@link edu.pa19.TerminationCreateInfo#getDir <em>Dir</em>}</li>
 * </ul>
 *
 * @see edu.pa19.Pa19Package#getTerminationCreateInfo()
 * @model kind="class"
 * @generated
 */
public class TerminationCreateInfo extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getCoord() <em>Coord</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoord()
   * @generated
   * @ordered
   */
  protected Coordinate coord;

  /**
   * The default value of the '{@link #getDir() <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDir()
   * @generated
   * @ordered
   */
  protected static final Direction DIR_EDEFAULT = Direction.UP;

  /**
   * The cached value of the '{@link #getDir() <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDir()
   * @generated
   * @ordered
   */
  protected Direction dir = DIR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TerminationCreateInfo()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.TERMINATION_CREATE_INFO;
  }

  /**
   * Returns the value of the '<em><b>Coord</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coord</em>' containment reference.
   * @see #setCoord(Coordinate)
   * @see edu.pa19.Pa19Package#getTerminationCreateInfo_Coord()
   * @model containment="true"
   * @generated
   */
  public Coordinate getCoord()
  {
    return coord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCoord(Coordinate newCoord, NotificationChain msgs)
  {
    Coordinate oldCoord = coord;
    coord = newCoord;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pa19Package.TERMINATION_CREATE_INFO__COORD, oldCoord, newCoord);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.pa19.TerminationCreateInfo#getCoord <em>Coord</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCoord the new value of the '<em>Coord</em>' containment reference.
   * @see #getCoord()
   * @generated
   */
  public void setCoord(Coordinate newCoord)
  {
    if (newCoord != coord)
    {
      NotificationChain msgs = null;
      if (coord != null)
        msgs = coord.eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Pa19Package.TERMINATION_CREATE_INFO__COORD, null, msgs);
      if (newCoord != null)
        msgs = newCoord.eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Pa19Package.TERMINATION_CREATE_INFO__COORD, null, msgs);
      msgs = basicSetCoord(newCoord, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.TERMINATION_CREATE_INFO__COORD, newCoord, newCoord));
  }

  /**
   * Returns the value of the '<em><b>Dir</b></em>' attribute.
   * The literals are from the enumeration {@link edu.pa19.Direction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dir</em>' attribute.
   * @see edu.pa19.Direction
   * @see #setDir(Direction)
   * @see edu.pa19.Pa19Package#getTerminationCreateInfo_Dir()
   * @model
   * @generated
   */
  public Direction getDir()
  {
    return dir;
  }

  /**
   * Sets the value of the '{@link edu.pa19.TerminationCreateInfo#getDir <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDir the new value of the '<em>Dir</em>' attribute.
   * @see edu.pa19.Direction
   * @see #getDir()
   * @generated
   */
  public void setDir(Direction newDir)
  {
    Direction oldDir = dir;
    dir = newDir == null ? DIR_EDEFAULT : newDir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pa19Package.TERMINATION_CREATE_INFO__DIR, oldDir, dir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pa19Package.TERMINATION_CREATE_INFO__COORD:
        return basicSetCoord(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pa19Package.TERMINATION_CREATE_INFO__COORD:
        return getCoord();
      case Pa19Package.TERMINATION_CREATE_INFO__DIR:
        return getDir();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pa19Package.TERMINATION_CREATE_INFO__COORD:
        setCoord((Coordinate)newValue);
        return;
      case Pa19Package.TERMINATION_CREATE_INFO__DIR:
        setDir((Direction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.TERMINATION_CREATE_INFO__COORD:
        setCoord((Coordinate)null);
        return;
      case Pa19Package.TERMINATION_CREATE_INFO__DIR:
        setDir(DIR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pa19Package.TERMINATION_CREATE_INFO__COORD:
        return coord != null;
      case Pa19Package.TERMINATION_CREATE_INFO__DIR:
        return dir != DIR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dir: ");
    result.append(dir);
    result.append(')');
    return result.toString();
  }

} // TerminationCreateInfo
