/**
 * generated by Enhanced EcoreGen
 */
package edu.pa19;

import org.eclipse.emf.ecore.EClass;
import util.PipePatterns;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wall</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Summary: Returns the character representation for a wall element.
 * Algorithm: Always returns the constant PipePatterns.WALL
 * Note: Requires an import of util.PipePatterns.
 * <!-- end-model-doc -->
 *
 *
 * @see edu.pa19.Pa19Package#getWall()
 * @model kind="class"
 * @generated
 */
public class Wall extends Cell
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Wall()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pa19Package.Literals.WALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns the wall character.
   * Algorithm:
   *   1. Return the wall character defined in PipePatterns (e.g., '#').
   * Related Features: None.
   * Related Classes: None.
   * Input: None.
   * Output: A character representing a wall (e.g., '#').
   * Pre-condition: None.
   * Post-condition: The wall state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public char toSingleChar()
  {
    return PipePatterns.WALL;
  }

} // Wall
